// Generated by tools/studio/variant-sets-build.mjs from docs/figma-contracts/component-properties.json (Figma 9nZv4uW2LT21yuHabMTCh1,
// read 2026-10-05), tools/studio/figma-props.map.mjs and inspector/figmaProps.generated.ts. Do not edit: run the script.

/** One VARIANT property of a Figma set: the code prop, the Figma name, its options in Figma order (`names`) and their
 *  code values (`values`; "true" / "false" for a Yes / No variant held as a boolean), and Figma's default. */
export type VariantAxis = { prop: string; label: string; names: readonly string[]; values: readonly string[]; default: string };
/** A Figma boolean that shows a layer: on sets `prop` to `on` (an icon name), off leaves it out. */
export type VariantToggle = { prop: string; label: string; on: string; default: boolean };
/** A Figma component set as the Main component frame draws it: `fixed` are the code props that pick this set
 *  (Button/Flat: appearance "flat"), `axes` its variant properties. */
export type VariantSet = { name: string; figma: string; fixed: Readonly<Record<string, string>>; axes: readonly VariantAxis[]; toggles: readonly VariantToggle[] };

export const VARIANT_SETS: Readonly<Record<string, readonly VariantSet[]>> = {
  "Button": [
    {
      "name": "Button/Main",
      "figma": "1026:8312",
      "fixed": {
        "appearance": "main"
      },
      "axes": [
        {
          "prop": "size",
          "label": "Size",
          "names": [
            "XLarge",
            "Large",
            "Medium (Base)",
            "Small",
            "XSmall"
          ],
          "values": [
            "xlarge",
            "large",
            "medium",
            "small",
            "xsmall"
          ],
          "default": "xlarge"
        },
        {
          "prop": "level",
          "label": "Level",
          "names": [
            "Primary",
            "Accent",
            "Secondary",
            "Tertiary",
            "Danger",
            "Danger Subtle",
            "Positive",
            "Positive Subtle",
            "Surface"
          ],
          "values": [
            "primary",
            "accent",
            "secondary",
            "tertiary",
            "danger",
            "danger-subtle",
            "positive",
            "positive-subtle",
            "surface"
          ],
          "default": "primary"
        },
        {
          "prop": "state",
          "label": "State",
          "names": [
            "Default",
            "Hover",
            "Pressed",
            "Focused",
            "Disabled"
          ],
          "values": [
            "default",
            "hover",
            "pressed",
            "focused",
            "disabled"
          ],
          "default": "default"
        }
      ],
      "toggles": [
        {
          "prop": "startIcon",
          "label": "Leading-Icon",
          "on": "icon-plus-line",
          "default": false
        },
        {
          "prop": "endIcon",
          "label": "Trailing-Icon",
          "on": "icon-plus-line",
          "default": false
        }
      ]
    },
    {
      "name": "Button/Flat",
      "figma": "1070:18754",
      "fixed": {
        "appearance": "flat"
      },
      "axes": [
        {
          "prop": "size",
          "label": "Size",
          "names": [
            "XLarge",
            "Large",
            "Medium (Base)",
            "Small",
            "XSmall"
          ],
          "values": [
            "xlarge",
            "large",
            "medium",
            "small",
            "xsmall"
          ],
          "default": "xlarge"
        },
        {
          "prop": "level",
          "label": "Level",
          "names": [
            "Primary",
            "Accent"
          ],
          "values": [
            "primary",
            "accent"
          ],
          "default": "primary"
        },
        {
          "prop": "state",
          "label": "State",
          "names": [
            "Default",
            "Hover",
            "Pressed",
            "Focused",
            "Disabled"
          ],
          "values": [
            "default",
            "hover",
            "pressed",
            "focused",
            "disabled"
          ],
          "default": "default"
        }
      ],
      "toggles": [
        {
          "prop": "startIcon",
          "label": "Leading-Icon",
          "on": "icon-plus-line",
          "default": false
        },
        {
          "prop": "endIcon",
          "label": "Trailing-Icon",
          "on": "icon-plus-line",
          "default": false
        }
      ]
    },
    {
      "name": "Button/Overlay",
      "figma": "1026:8747",
      "fixed": {
        "appearance": "overlay"
      },
      "axes": [
        {
          "prop": "size",
          "label": "Size",
          "names": [
            "XLarge",
            "Large",
            "Medium (Base)",
            "Small",
            "XSmall"
          ],
          "values": [
            "xlarge",
            "large",
            "medium",
            "small",
            "xsmall"
          ],
          "default": "xlarge"
        },
        {
          "prop": "level",
          "label": "Level",
          "names": [
            "Inverse",
            "White",
            "White Overlay",
            "Black Overlay"
          ],
          "values": [
            "inverse",
            "white",
            "white-overlay",
            "black-overlay"
          ],
          "default": "inverse"
        },
        {
          "prop": "state",
          "label": "State",
          "names": [
            "Default",
            "Hover",
            "Pressed",
            "Focused",
            "Disabled"
          ],
          "values": [
            "default",
            "hover",
            "pressed",
            "focused",
            "disabled"
          ],
          "default": "default"
        }
      ],
      "toggles": [
        {
          "prop": "startIcon",
          "label": "Leading-Icon",
          "on": "icon-plus-line",
          "default": false
        },
        {
          "prop": "endIcon",
          "label": "Trailing-Icon",
          "on": "icon-plus-line",
          "default": false
        }
      ]
    }
  ],
  "IconButton": [
    {
      "name": "Button/Icon-Main",
      "figma": "205:21062",
      "fixed": {
        "appearance": "main"
      },
      "axes": [
        {
          "prop": "size",
          "label": "Size",
          "names": [
            "XLarge",
            "Large",
            "Medium",
            "Small",
            "XSmall",
            "2XSmall"
          ],
          "values": [
            "xlarge",
            "large",
            "medium",
            "small",
            "xsmall",
            "2xsmall"
          ],
          "default": "xlarge"
        },
        {
          "prop": "level",
          "label": "Level",
          "names": [
            "Primary",
            "Accent",
            "Secondary",
            "Tertiary",
            "Danger",
            "Danger Secondary",
            "Positive",
            "Positive Secondary",
            "Surface"
          ],
          "values": [
            "primary",
            "accent",
            "secondary",
            "tertiary",
            "danger",
            "danger-secondary",
            "positive",
            "positive-secondary",
            "surface"
          ],
          "default": "primary"
        },
        {
          "prop": "state",
          "label": "State",
          "names": [
            "Default",
            "Hover",
            "Pressed",
            "Focused",
            "Disabled"
          ],
          "values": [
            "default",
            "hover",
            "pressed",
            "focused",
            "disabled"
          ],
          "default": "default"
        }
      ],
      "toggles": []
    },
    {
      "name": "Button/Icon-Flat",
      "figma": "234:43906",
      "fixed": {
        "appearance": "flat"
      },
      "axes": [
        {
          "prop": "size",
          "label": "Size",
          "names": [
            "XLarge",
            "Large",
            "Medium",
            "Small",
            "XSmall"
          ],
          "values": [
            "xlarge",
            "large",
            "medium",
            "small",
            "xsmall"
          ],
          "default": "xlarge"
        },
        {
          "prop": "level",
          "label": "Level",
          "names": [
            "Primary",
            "Secondary",
            "Accent",
            "Danger",
            "Positive"
          ],
          "values": [
            "primary",
            "secondary",
            "accent",
            "danger",
            "positive"
          ],
          "default": "primary"
        },
        {
          "prop": "state",
          "label": "State",
          "names": [
            "Default",
            "Hover",
            "Pressed",
            "Focused",
            "Disabled"
          ],
          "values": [
            "default",
            "hover",
            "pressed",
            "focused",
            "disabled"
          ],
          "default": "default"
        }
      ],
      "toggles": []
    },
    {
      "name": "Button/Icon-Overlay",
      "figma": "291:41855",
      "fixed": {
        "appearance": "overlay"
      },
      "axes": [
        {
          "prop": "size",
          "label": "Size",
          "names": [
            "XLarge",
            "Large",
            "Medium",
            "Small",
            "XSmall",
            "2XSmall"
          ],
          "values": [
            "xlarge",
            "large",
            "medium",
            "small",
            "xsmall",
            "2xsmall"
          ],
          "default": "xlarge"
        },
        {
          "prop": "level",
          "label": "Level",
          "names": [
            "Inverse",
            "White",
            "White Overlay",
            "Black Overlay"
          ],
          "values": [
            "inverse",
            "white",
            "white-overlay",
            "black-overlay"
          ],
          "default": "inverse"
        },
        {
          "prop": "state",
          "label": "State",
          "names": [
            "Default",
            "Hover",
            "Pressed",
            "Focused",
            "Disabled"
          ],
          "values": [
            "default",
            "hover",
            "pressed",
            "focused",
            "disabled"
          ],
          "default": "default"
        }
      ],
      "toggles": []
    }
  ],
  "Avatar": [
    {
      "name": "Avatar/Single",
      "figma": "223:9050",
      "fixed": {},
      "axes": [
        {
          "prop": "shape",
          "label": "Shape",
          "names": [
            "Circle",
            "Square"
          ],
          "values": [
            "circle",
            "square"
          ],
          "default": "circle"
        },
        {
          "prop": "size",
          "label": "Size",
          "names": [
            "3XLarge",
            "2XLarge",
            "XLarge",
            "Large",
            "Medium",
            "Small",
            "XSmall",
            "2XSmall"
          ],
          "values": [
            "3xlarge",
            "2xlarge",
            "xlarge",
            "large",
            "medium",
            "small",
            "xsmall",
            "2xsmall"
          ],
          "default": "3xlarge"
        },
        {
          "prop": "theme",
          "label": "Theme",
          "names": [
            "Photo",
            "Accent",
            "Blue",
            "Brown",
            "Crimson",
            "Cyan",
            "Green",
            "Indigo",
            "Neutral",
            "Orange",
            "Pink",
            "Plum",
            "Purple",
            "Red",
            "Teal",
            "Violet",
            "Yellow"
          ],
          "values": [
            "photo",
            "accent",
            "blue",
            "brown",
            "crimson",
            "cyan",
            "green",
            "indigo",
            "neutral",
            "orange",
            "pink",
            "plum",
            "purple",
            "red",
            "teal",
            "violet",
            "yellow"
          ],
          "default": "photo"
        },
        {
          "prop": "background",
          "label": "Background",
          "names": [
            "Solid",
            "Subtle"
          ],
          "values": [
            "solid",
            "subtle"
          ],
          "default": "subtle"
        }
      ],
      "toggles": []
    }
  ],
  "AvatarStack": [
    {
      "name": "Avatar/Stack",
      "figma": "364:92561",
      "fixed": {},
      "axes": [
        {
          "prop": "size",
          "label": "Size",
          "names": [
            "Medium",
            "Small"
          ],
          "values": [
            "medium",
            "small"
          ],
          "default": "medium"
        },
        {
          "prop": "background",
          "label": "Background",
          "names": [
            "Subtle",
            "Solid"
          ],
          "values": [
            "subtle",
            "solid"
          ],
          "default": "subtle"
        }
      ],
      "toggles": []
    }
  ],
  "Accordion": [
    {
      "name": "Accordion/Text",
      "figma": "239:16847",
      "fixed": {},
      "axes": [
        {
          "prop": "size",
          "label": "Size",
          "names": [
            "XLarge",
            "Large",
            "Medium"
          ],
          "values": [
            "xlarge",
            "large",
            "medium"
          ],
          "default": "xlarge"
        },
        {
          "prop": "theme",
          "label": "Theme",
          "names": [
            "Divider",
            "Box"
          ],
          "values": [
            "divider",
            "box"
          ],
          "default": "divider"
        },
        {
          "prop": "expanded",
          "label": "Expanded",
          "names": [
            "No",
            "Yes"
          ],
          "values": [
            "false",
            "true"
          ],
          "default": "false"
        },
        {
          "prop": "contentWidth",
          "label": "Content Width",
          "names": [
            "Title",
            "Full"
          ],
          "values": [
            "title",
            "full"
          ],
          "default": "title"
        }
      ],
      "toggles": []
    }
  ],
  "AlertBanner": [
    {
      "name": "Alert-Banner",
      "figma": "6828:9393",
      "fixed": {},
      "axes": [
        {
          "prop": "size",
          "label": "Size",
          "names": [
            "Medium",
            "Small"
          ],
          "values": [
            "medium",
            "small"
          ],
          "default": "medium"
        },
        {
          "prop": "theme",
          "label": "Theme",
          "names": [
            "Default",
            "Info",
            "Positive",
            "Warning",
            "Negative"
          ],
          "values": [
            "default",
            "info",
            "positive",
            "warning",
            "negative"
          ],
          "default": "default"
        }
      ],
      "toggles": []
    }
  ],
  "Badge": [
    {
      "name": "Badge",
      "figma": "260:4825",
      "fixed": {},
      "axes": [
        {
          "prop": "size",
          "label": "Size",
          "names": [
            "Medium",
            "Small",
            "XSmall"
          ],
          "values": [
            "medium",
            "small",
            "xsmall"
          ],
          "default": "medium"
        },
        {
          "prop": "theme",
          "label": "Theme",
          "names": [
            "Accent",
            "Neutral",
            "Yellow",
            "Orange",
            "Red",
            "Crimson",
            "Pink",
            "Plum",
            "Purple",
            "Violet",
            "Indigo",
            "Blue",
            "Cyan",
            "Teal",
            "Green",
            "Brown",
            "Inverse",
            "On-Color"
          ],
          "values": [
            "accent",
            "neutral",
            "yellow",
            "orange",
            "red",
            "crimson",
            "pink",
            "plum",
            "purple",
            "violet",
            "indigo",
            "blue",
            "cyan",
            "teal",
            "green",
            "brown",
            "inverse",
            "on-color"
          ],
          "default": "neutral"
        },
        {
          "prop": "background",
          "label": "Background",
          "names": [
            "Solid",
            "Subtle"
          ],
          "values": [
            "solid",
            "subtle"
          ],
          "default": "solid"
        }
      ],
      "toggles": []
    }
  ],
  "BadgeCounter": [
    {
      "name": "Badge-Counter",
      "figma": "9535:33812",
      "fixed": {},
      "axes": [
        {
          "prop": "size",
          "label": "Size",
          "names": [
            "Medium",
            "Small",
            "XSmall"
          ],
          "values": [
            "medium",
            "small",
            "xsmall"
          ],
          "default": "medium"
        },
        {
          "prop": "theme",
          "label": "Theme",
          "names": [
            "Accent",
            "Neutral",
            "Yellow",
            "Orange",
            "Red",
            "Crimson",
            "Pink",
            "Plum",
            "Purple",
            "Violet",
            "Indigo",
            "Blue",
            "Cyan",
            "Teal",
            "Green",
            "Brown",
            "Inverse",
            "On-Color"
          ],
          "values": [
            "accent",
            "neutral",
            "yellow",
            "orange",
            "red",
            "crimson",
            "pink",
            "plum",
            "purple",
            "violet",
            "indigo",
            "blue",
            "cyan",
            "teal",
            "green",
            "brown",
            "inverse",
            "on-color"
          ],
          "default": "neutral"
        },
        {
          "prop": "background",
          "label": "Background",
          "names": [
            "Solid",
            "Subtle"
          ],
          "values": [
            "solid",
            "subtle"
          ],
          "default": "solid"
        }
      ],
      "toggles": []
    }
  ],
  "BottomSheet": [
    {
      "name": "Bottom-Sheet",
      "figma": "4059:14161",
      "fixed": {},
      "axes": [
        {
          "prop": "type",
          "label": "Type",
          "names": [
            "Modal",
            "Action"
          ],
          "values": [
            "modal",
            "action"
          ],
          "default": "action"
        },
        {
          "prop": "size",
          "label": "Size",
          "names": [
            "Flex",
            "Max-Fixed"
          ],
          "values": [
            "flex",
            "max"
          ],
          "default": "flex"
        }
      ],
      "toggles": [
        {
          "prop": "title",
          "label": "Header",
          "on": "Title",
          "default": true
        }
      ]
    }
  ],
  "Card": [
    {
      "name": "Card",
      "figma": "6643:51021",
      "fixed": {},
      "axes": [
        {
          "prop": "theme",
          "label": "Theme",
          "names": [
            "Shadow",
            "Flat",
            "Pale",
            "Border",
            "Semi-Pale"
          ],
          "values": [
            "shadow",
            "flat",
            "pale",
            "border",
            "semi-pale"
          ],
          "default": "shadow"
        },
        {
          "prop": "spacing",
          "label": "Spacing",
          "names": [
            "Medium",
            "Small"
          ],
          "values": [
            "medium",
            "small"
          ],
          "default": "medium"
        },
        {
          "prop": "active",
          "label": "Active",
          "names": [
            "No",
            "Yes"
          ],
          "values": [
            "false",
            "true"
          ],
          "default": "false"
        }
      ],
      "toggles": []
    }
  ],
  "Chip": [
    {
      "name": "Chip/Normal",
      "figma": "512:6843",
      "fixed": {
        "variant": "normal"
      },
      "axes": [
        {
          "prop": "size",
          "label": "Size",
          "names": [
            "Medium",
            "Small",
            "XSmall"
          ],
          "values": [
            "medium",
            "small",
            "xsmall"
          ],
          "default": "small"
        },
        {
          "prop": "level",
          "label": "Level",
          "names": [
            "Primary",
            "Secondary"
          ],
          "values": [
            "primary",
            "secondary"
          ],
          "default": "secondary"
        },
        {
          "prop": "theme",
          "label": "Theme",
          "names": [
            "Text-Only",
            "Leading-Icon",
            "Leading-Photo"
          ],
          "values": [
            "text-only",
            "leading-icon",
            "leading-photo"
          ],
          "default": "text-only"
        },
        {
          "prop": "state",
          "label": "State",
          "names": [
            "Default",
            "Hover",
            "Focused"
          ],
          "values": [
            "default",
            "hover",
            "focused"
          ],
          "default": "default"
        },
        {
          "prop": "selected",
          "label": "Select",
          "names": [
            "No",
            "Yes"
          ],
          "values": [
            "false",
            "true"
          ],
          "default": "false"
        }
      ],
      "toggles": []
    },
    {
      "name": "Chip/Advanced",
      "figma": "512:7659",
      "fixed": {
        "variant": "advanced"
      },
      "axes": [
        {
          "prop": "size",
          "label": "Size",
          "names": [
            "Medium",
            "Small"
          ],
          "values": [
            "medium",
            "small"
          ],
          "default": "small"
        },
        {
          "prop": "theme",
          "label": "Theme",
          "names": [
            "Text-Only",
            "Leading-Icon",
            "Leading-Photo"
          ],
          "values": [
            "text-only",
            "leading-icon",
            "leading-photo"
          ],
          "default": "text-only"
        },
        {
          "prop": "state",
          "label": "State",
          "names": [
            "Default",
            "Hover",
            "Press",
            "Focused",
            "Placeholder"
          ],
          "values": [
            "default",
            "hover",
            "press",
            "focused",
            "placeholder"
          ],
          "default": "default"
        },
        {
          "prop": "selected",
          "label": "Select",
          "names": [
            "No",
            "Yes"
          ],
          "values": [
            "false",
            "true"
          ],
          "default": "false"
        }
      ],
      "toggles": []
    },
    {
      "name": "Chip/Number-Only",
      "figma": "1536:26687",
      "fixed": {
        "variant": "number-only"
      },
      "axes": [
        {
          "prop": "size",
          "label": "Size",
          "names": [
            "Medium",
            "Small"
          ],
          "values": [
            "medium",
            "small"
          ],
          "default": "small"
        },
        {
          "prop": "level",
          "label": "Level",
          "names": [
            "Primary",
            "Secondary"
          ],
          "values": [
            "primary",
            "secondary"
          ],
          "default": "secondary"
        },
        {
          "prop": "state",
          "label": "State",
          "names": [
            "Default",
            "Hover",
            "Focused"
          ],
          "values": [
            "default",
            "hover",
            "focused"
          ],
          "default": "default"
        },
        {
          "prop": "selected",
          "label": "Select",
          "names": [
            "No",
            "Yes"
          ],
          "values": [
            "false",
            "true"
          ],
          "default": "false"
        }
      ],
      "toggles": []
    }
  ],
  "Checkbox": [
    {
      "name": "Checkbox/Text",
      "figma": "309:46871",
      "fixed": {},
      "axes": [
        {
          "prop": "state",
          "label": "State",
          "names": [
            "Default",
            "Hover",
            "Focus",
            "Disabled"
          ],
          "values": [
            "default",
            "hover",
            "focus",
            "disabled"
          ],
          "default": "default"
        },
        {
          "prop": "checked",
          "label": "Select",
          "names": [
            "No",
            "Yes"
          ],
          "values": [
            "false",
            "true"
          ],
          "default": "false"
        },
        {
          "prop": "checkSide",
          "label": "Check-Side",
          "names": [
            "Left",
            "Right"
          ],
          "values": [
            "left",
            "right"
          ],
          "default": "left"
        }
      ],
      "toggles": [
        {
          "prop": "caption",
          "label": "Caption",
          "on": "Caption",
          "default": false
        }
      ]
    }
  ],
  "Divider": [
    {
      "name": "Divider",
      "figma": "460:38361",
      "fixed": {},
      "axes": [
        {
          "prop": "color",
          "label": "Color",
          "names": [
            "Default",
            "Medium",
            "High"
          ],
          "values": [
            "default",
            "medium",
            "high"
          ],
          "default": "default"
        }
      ],
      "toggles": []
    }
  ],
  "DockIcon": [
    {
      "name": "Dock-Icon",
      "figma": "308:45902",
      "fixed": {},
      "axes": [
        {
          "prop": "size",
          "label": "Size",
          "names": [
            "XLarge",
            "Large",
            "Medium",
            "Small",
            "XSmall"
          ],
          "values": [
            "xlarge",
            "large",
            "medium",
            "small",
            "xsmall"
          ],
          "default": "xlarge"
        },
        {
          "prop": "theme",
          "label": "Theme",
          "names": [
            "Accent",
            "Blue",
            "Brown",
            "Crimson",
            "Cyan",
            "Green",
            "Indigo",
            "Neutral",
            "Orange",
            "Pink",
            "Plum",
            "Purple",
            "Red",
            "Teal",
            "Violet",
            "Yellow",
            "On-Color",
            "Emoji",
            "Golden",
            "Inverse",
            "Pale",
            "Surface"
          ],
          "values": [
            "accent",
            "blue",
            "brown",
            "crimson",
            "cyan",
            "green",
            "indigo",
            "neutral",
            "orange",
            "pink",
            "plum",
            "purple",
            "red",
            "teal",
            "violet",
            "yellow",
            "on-color",
            "emoji",
            "golden",
            "inverse",
            "pale",
            "surface"
          ],
          "default": "neutral"
        },
        {
          "prop": "background",
          "label": "Background",
          "names": [
            "Solid",
            "Subtle"
          ],
          "values": [
            "solid",
            "subtle"
          ],
          "default": "solid"
        }
      ],
      "toggles": []
    }
  ],
  "DescriptionList": [
    {
      "name": "Description List",
      "figma": "14859:79180",
      "fixed": {},
      "axes": [
        {
          "prop": "layout",
          "label": "Layout",
          "names": [
            "Inline",
            "Stacked"
          ],
          "values": [
            "inline",
            "stacked"
          ],
          "default": "inline"
        },
        {
          "prop": "divider",
          "label": "Divider",
          "names": [
            "No",
            "Yes"
          ],
          "values": [
            "false",
            "true"
          ],
          "default": "false"
        }
      ],
      "toggles": []
    }
  ],
  "InputField": [
    {
      "name": "Input/Text-Field",
      "figma": "421:4108",
      "fixed": {},
      "axes": [
        {
          "prop": "size",
          "label": "Size",
          "names": [
            "Small",
            "Medium (Base)",
            "Large",
            "XLarge"
          ],
          "values": [
            "small",
            "medium",
            "large",
            "xlarge"
          ],
          "default": "medium"
        },
        {
          "prop": "state",
          "label": "State",
          "names": [
            "Default",
            "Hover",
            "Focused",
            "Typing",
            "Inputted",
            "Read-Only",
            "Disabled",
            "Inputted-Error",
            "Blank-Error"
          ],
          "values": [
            "default",
            "hover",
            "focused",
            "typing",
            "inputted",
            "read-only",
            "disabled",
            "inputted-error",
            "blank-error"
          ],
          "default": "default"
        }
      ],
      "toggles": [
        {
          "prop": "helpText",
          "label": "Help-Text",
          "on": "Help text",
          "default": false
        },
        {
          "prop": "label",
          "label": "Label",
          "on": "Label",
          "default": true
        }
      ]
    }
  ],
  "SelectField": [
    {
      "name": "Input/Select-Field",
      "figma": "421:7303",
      "fixed": {},
      "axes": [
        {
          "prop": "size",
          "label": "Size",
          "names": [
            "Small",
            "Medium (Base)",
            "Large",
            "XLarge"
          ],
          "values": [
            "small",
            "medium",
            "large",
            "xlarge"
          ],
          "default": "medium"
        },
        {
          "prop": "state",
          "label": "State",
          "names": [
            "Default",
            "Hover",
            "Focused",
            "Typing",
            "Inputted",
            "Read-Only",
            "Disabled",
            "Inputted-Error",
            "Blank-Error"
          ],
          "values": [
            "default",
            "hover",
            "focused",
            "typing",
            "inputted",
            "read-only",
            "disabled",
            "inputted-error",
            "blank-error"
          ],
          "default": "default"
        }
      ],
      "toggles": [
        {
          "prop": "helpText",
          "label": "Help-Text",
          "on": "Help text",
          "default": false
        },
        {
          "prop": "label",
          "label": "Label",
          "on": "Label",
          "default": true
        }
      ]
    }
  ],
  "DateField": [
    {
      "name": "Input/Date-Field",
      "figma": "421:8388",
      "fixed": {},
      "axes": [
        {
          "prop": "size",
          "label": "Size",
          "names": [
            "Small",
            "Medium (Base)",
            "Large",
            "XLarge"
          ],
          "values": [
            "small",
            "medium",
            "large",
            "xlarge"
          ],
          "default": "medium"
        },
        {
          "prop": "state",
          "label": "State",
          "names": [
            "Default",
            "Hover",
            "Focused",
            "Typing",
            "Inputted",
            "Read-Only",
            "Disabled",
            "Inputted-Error",
            "Blank-Error"
          ],
          "values": [
            "default",
            "hover",
            "focused",
            "typing",
            "inputted",
            "read-only",
            "disabled",
            "inputted-error",
            "blank-error"
          ],
          "default": "default"
        }
      ],
      "toggles": [
        {
          "prop": "helpText",
          "label": "Help-Text",
          "on": "Help text",
          "default": false
        },
        {
          "prop": "label",
          "label": "Label",
          "on": "Label",
          "default": true
        }
      ]
    }
  ],
  "HeadingField": [
    {
      "name": "Input/Heading",
      "figma": "694:13062",
      "fixed": {},
      "axes": [
        {
          "prop": "status",
          "label": "Status",
          "names": [
            "Default",
            "Hover",
            "Focus",
            "Typing",
            "Inputted-Single-Line",
            "Inputted-Multi-Line",
            "Inputted-Hover"
          ],
          "values": [
            "default",
            "hover",
            "focus",
            "typing",
            "inputted-single-line",
            "inputted-multi-line",
            "inputted-hover"
          ],
          "default": "default"
        },
        {
          "prop": "headingSize",
          "label": "Size",
          "names": [
            "H1",
            "H2",
            "H3"
          ],
          "values": [
            "h1",
            "h2",
            "h3"
          ],
          "default": "h3"
        }
      ],
      "toggles": []
    }
  ],
  "InlineMessage": [
    {
      "name": "Inline-Message",
      "figma": "595:54857",
      "fixed": {},
      "axes": [
        {
          "prop": "theme",
          "label": "Theme",
          "names": [
            "Neutral",
            "Info",
            "Warning",
            "Negative",
            "Custom"
          ],
          "values": [
            "neutral",
            "info",
            "warning",
            "negative",
            "custom"
          ],
          "default": "neutral"
        }
      ],
      "toggles": [
        {
          "prop": "title",
          "label": "Title",
          "on": "Title",
          "default": true
        }
      ]
    }
  ],
  "Dialog": [
    {
      "name": "Modal/Dialog",
      "figma": "841:17177",
      "fixed": {},
      "axes": [
        {
          "prop": "theme",
          "label": "Theme",
          "names": [
            "Default",
            "Info",
            "Positive",
            "Warning",
            "Negative"
          ],
          "values": [
            "default",
            "info",
            "positive",
            "warning",
            "negative"
          ],
          "default": "default"
        }
      ],
      "toggles": [
        {
          "prop": "description",
          "label": "Caption",
          "on": "Description",
          "default": true
        }
      ]
    }
  ],
  "ModalForm": [
    {
      "name": "Modal/Forms",
      "figma": "841:17182",
      "fixed": {},
      "axes": [
        {
          "prop": "layout",
          "label": "Layout",
          "names": [
            "Basic",
            "1-3",
            "Half-Half",
            "3-4",
            "Big"
          ],
          "values": [
            "basic",
            "1-3",
            "half-half",
            "3-4",
            "big"
          ],
          "default": "basic"
        }
      ],
      "toggles": [
        {
          "prop": "description",
          "label": "Caption",
          "on": "Description",
          "default": true
        }
      ]
    }
  ],
  "ProgressBar": [
    {
      "name": "Progress-Bar",
      "figma": "1536:260",
      "fixed": {},
      "axes": [
        {
          "prop": "theme",
          "label": "Theme",
          "names": [
            "Accent",
            "Neutral",
            "Status"
          ],
          "values": [
            "accent",
            "neutral",
            "status"
          ],
          "default": "neutral"
        }
      ],
      "toggles": [
        {
          "prop": "label",
          "label": "Label",
          "on": "Label",
          "default": true
        }
      ]
    }
  ],
  "Pagination": [
    {
      "name": "Pagination",
      "figma": "774:29083",
      "fixed": {},
      "axes": [
        {
          "prop": "theme",
          "label": "Theme",
          "names": [
            "Primary",
            "Secondary",
            "Inline",
            "Manually"
          ],
          "values": [
            "primary",
            "secondary",
            "inline",
            "manually"
          ],
          "default": "primary"
        }
      ],
      "toggles": []
    }
  ],
  "Rating": [
    {
      "name": "Rating/Star",
      "figma": "1536:26008",
      "fixed": {},
      "axes": [
        {
          "prop": "size",
          "label": "Size",
          "names": [
            "XSmall",
            "Small",
            "Medium",
            "Large",
            "XLarge"
          ],
          "values": [
            "xsmall",
            "small",
            "medium",
            "large",
            "xlarge"
          ],
          "default": "xlarge"
        },
        {
          "prop": "theme",
          "label": "Theme",
          "names": [
            "Default",
            "Neutral",
            "Accent"
          ],
          "values": [
            "default",
            "neutral",
            "accent"
          ],
          "default": "default"
        }
      ],
      "toggles": []
    }
  ],
  "RatingDisplay": [
    {
      "name": "Rating-Display",
      "figma": "9818:5582",
      "fixed": {},
      "axes": [
        {
          "prop": "size",
          "label": "Size",
          "names": [
            "XLarge",
            "Large",
            "Medium",
            "Small",
            "XSmall"
          ],
          "values": [
            "xlarge",
            "large",
            "medium",
            "small",
            "xsmall"
          ],
          "default": "xlarge"
        },
        {
          "prop": "theme",
          "label": "Theme",
          "names": [
            "Neutral",
            "Default",
            "Accent"
          ],
          "values": [
            "neutral",
            "default",
            "accent"
          ],
          "default": "neutral"
        }
      ],
      "toggles": []
    }
  ],
  "OpinionScale": [
    {
      "name": "Rating/Opinion-Scale",
      "figma": "1536:25762",
      "fixed": {},
      "axes": [
        {
          "prop": "scale",
          "label": "Scale",
          "names": [
            "2",
            "3",
            "5"
          ],
          "values": [
            "2",
            "3",
            "5"
          ],
          "default": "2"
        }
      ],
      "toggles": []
    }
  ],
  "NpsScale": [
    {
      "name": "Rating/NPS-Scale",
      "figma": "1536:26034",
      "fixed": {},
      "axes": [
        {
          "prop": "scale",
          "label": "Scale",
          "names": [
            "5",
            "10"
          ],
          "values": [
            "5",
            "10"
          ],
          "default": "5"
        }
      ],
      "toggles": []
    }
  ],
  "RadioButton": [
    {
      "name": "Radio-Button/Radio-Button",
      "figma": "373:96272",
      "fixed": {},
      "axes": [
        {
          "prop": "state",
          "label": "State",
          "names": [
            "Default",
            "Hover",
            "Focus",
            "Disabled"
          ],
          "values": [
            "default",
            "hover",
            "focus",
            "disabled"
          ],
          "default": "default"
        },
        {
          "prop": "checked",
          "label": "Select",
          "names": [
            "No",
            "Yes"
          ],
          "values": [
            "false",
            "true"
          ],
          "default": "false"
        },
        {
          "prop": "radioSide",
          "label": "Radio-Side",
          "names": [
            "Left",
            "Right"
          ],
          "values": [
            "left",
            "right"
          ],
          "default": "left"
        }
      ],
      "toggles": []
    }
  ],
  "Search": [
    {
      "name": "Search/Default",
      "figma": "846:37624",
      "fixed": {
        "variant": "default"
      },
      "axes": [
        {
          "prop": "size",
          "label": "Size",
          "names": [
            "Medium",
            "Small"
          ],
          "values": [
            "medium",
            "small"
          ],
          "default": "small"
        },
        {
          "prop": "theme",
          "label": "Theme",
          "names": [
            "Default",
            "Filter-Icon",
            "Filter-Dropdown"
          ],
          "values": [
            "default",
            "filter-icon",
            "filter-dropdown"
          ],
          "default": "default"
        },
        {
          "prop": "state",
          "label": "State",
          "names": [
            "Default",
            "Hover",
            "Focused",
            "Typing",
            "Inputted"
          ],
          "values": [
            "default",
            "hover",
            "focused",
            "typing",
            "inputted"
          ],
          "default": "default"
        },
        {
          "prop": "iconSearch",
          "label": "Icon-Search",
          "names": [
            "Yes",
            "No"
          ],
          "values": [
            "true",
            "false"
          ],
          "default": "true"
        }
      ],
      "toggles": []
    },
    {
      "name": "Search/Popover",
      "figma": "1604:27401",
      "fixed": {
        "variant": "popover"
      },
      "axes": [
        {
          "prop": "theme",
          "label": "Theme",
          "names": [
            "Default",
            "Filter-Icon",
            "Filter-Dropdown"
          ],
          "values": [
            "default",
            "filter-icon",
            "filter-dropdown"
          ],
          "default": "default"
        },
        {
          "prop": "state",
          "label": "State",
          "names": [
            "Default",
            "Hover",
            "Focused",
            "Typing",
            "Inputted"
          ],
          "values": [
            "default",
            "hover",
            "focused",
            "typing",
            "inputted"
          ],
          "default": "default"
        },
        {
          "prop": "iconSearch",
          "label": "Icon-Search",
          "names": [
            "Yes",
            "No"
          ],
          "values": [
            "true",
            "false"
          ],
          "default": "true"
        }
      ],
      "toggles": []
    }
  ],
  "Slider": [
    {
      "name": "Slider/Horizontal",
      "figma": "4010:35946",
      "fixed": {},
      "axes": [
        {
          "prop": "theme",
          "label": "Theme",
          "names": [
            "Neutral",
            "Accent",
            "White"
          ],
          "values": [
            "neutral",
            "accent",
            "white"
          ],
          "default": "neutral"
        },
        {
          "prop": "size",
          "label": "Size",
          "names": [
            "Small",
            "Medium",
            "Large"
          ],
          "values": [
            "small",
            "medium",
            "large"
          ],
          "default": "small"
        }
      ],
      "toggles": []
    }
  ],
  "Sidebar": [
    {
      "name": "Side-Bar/Master/Basic",
      "figma": "4081:15234",
      "fixed": {
        "variant": "basic"
      },
      "axes": [],
      "toggles": []
    },
    {
      "name": "Side-Bar/Master/Workspace",
      "figma": "4218:9166",
      "fixed": {
        "variant": "workspace"
      },
      "axes": [
        {
          "prop": "background",
          "label": "Master-Background",
          "names": [
            "Flat",
            "Default",
            "Inverse"
          ],
          "values": [
            "flat",
            "default",
            "inverse"
          ],
          "default": "flat"
        }
      ],
      "toggles": []
    },
    {
      "name": "Side-Bar/Master/Small-Density",
      "figma": "5974:20590",
      "fixed": {
        "variant": "small-density"
      },
      "axes": [],
      "toggles": []
    }
  ],
  "SkeletonHeading": [
    {
      "name": "Skeleton/Heading-Text",
      "figma": "1556:17593",
      "fixed": {},
      "axes": [
        {
          "prop": "size",
          "label": "Size",
          "names": [
            "Large",
            "Medium",
            "Small"
          ],
          "values": [
            "large",
            "medium",
            "small"
          ],
          "default": "large"
        }
      ],
      "toggles": []
    }
  ],
  "SkeletonShape": [
    {
      "name": "Skeleton/Shapes",
      "figma": "1556:17525",
      "fixed": {},
      "axes": [
        {
          "prop": "shape",
          "label": "Shape",
          "names": [
            "Pill",
            "Round",
            "Square",
            "Rectangle"
          ],
          "values": [
            "pill",
            "round",
            "square",
            "rectangle"
          ],
          "default": "round"
        },
        {
          "prop": "size",
          "label": "Size",
          "names": [
            "Large - 48px",
            "Medium - 40px",
            "Small - 32px",
            "XSmall",
            "2XSmall"
          ],
          "values": [
            "large",
            "medium",
            "small",
            "xsmall",
            "2xsmall"
          ],
          "default": "large"
        }
      ],
      "toggles": []
    }
  ],
  "Segmented": [
    {
      "name": "Segmented",
      "figma": "1238:892",
      "fixed": {},
      "axes": [
        {
          "prop": "level",
          "label": "Level",
          "names": [
            "Secondary",
            "Primary"
          ],
          "values": [
            "secondary",
            "primary"
          ],
          "default": "secondary"
        }
      ],
      "toggles": []
    }
  ],
  "SidePanel": [
    {
      "name": "Side-Panel",
      "figma": "1573:3128",
      "fixed": {},
      "axes": [
        {
          "prop": "type",
          "label": "Type",
          "names": [
            "Modal",
            "Standard"
          ],
          "values": [
            "modal",
            "standard"
          ],
          "default": "standard"
        },
        {
          "prop": "size",
          "label": "Size",
          "names": [
            "Default",
            "Small"
          ],
          "values": [
            "default",
            "small"
          ],
          "default": "small"
        }
      ],
      "toggles": []
    }
  ],
  "Tabs": [
    {
      "name": "Tab-Bar",
      "figma": "1577:5477",
      "fixed": {},
      "axes": [
        {
          "prop": "variant",
          "label": "Style",
          "names": [
            "Indicator",
            "Subtle"
          ],
          "values": [
            "indicator",
            "subtle"
          ],
          "default": "indicator"
        }
      ],
      "toggles": []
    }
  ],
  "Tag": [
    {
      "name": "Tag",
      "figma": "288:32046",
      "fixed": {},
      "axes": [
        {
          "prop": "state",
          "label": "State",
          "names": [
            "Default",
            "Hover",
            "Focused",
            "Error",
            "Disabled"
          ],
          "values": [
            "default",
            "hover",
            "focused",
            "error",
            "disabled"
          ],
          "default": "default"
        },
        {
          "prop": "remove",
          "label": "Remove",
          "names": [
            "No",
            "Yes"
          ],
          "values": [
            "false",
            "true"
          ],
          "default": "false"
        }
      ],
      "toggles": []
    }
  ],
  "Toggle": [
    {
      "name": "Toggle",
      "figma": "1526:5703",
      "fixed": {},
      "axes": [
        {
          "prop": "size",
          "label": "Size",
          "names": [
            "Small",
            "Medium",
            "Large"
          ],
          "values": [
            "small",
            "medium",
            "large"
          ],
          "default": "small"
        },
        {
          "prop": "state",
          "label": "State",
          "names": [
            "Default",
            "Disabled"
          ],
          "values": [
            "default",
            "disabled"
          ],
          "default": "default"
        },
        {
          "prop": "checked",
          "label": "Select",
          "names": [
            "No",
            "Yes"
          ],
          "values": [
            "false",
            "true"
          ],
          "default": "false"
        },
        {
          "prop": "theme",
          "label": "Theme",
          "names": [
            "Text-First",
            "Toggle-First"
          ],
          "values": [
            "text-first",
            "toggle-first"
          ],
          "default": "text-first"
        }
      ],
      "toggles": []
    }
  ],
  "ToggleButton": [
    {
      "name": "Toggle-Button",
      "figma": "1523:104",
      "fixed": {},
      "axes": [
        {
          "prop": "size",
          "label": "Size",
          "names": [
            "Large",
            "Medium",
            "Small"
          ],
          "values": [
            "large",
            "medium",
            "small"
          ],
          "default": "medium"
        },
        {
          "prop": "state",
          "label": "State",
          "names": [
            "Default",
            "Disabled",
            "Default-Hover"
          ],
          "values": [
            "default",
            "disabled",
            "hover"
          ],
          "default": "default"
        },
        {
          "prop": "checked",
          "label": "Select",
          "names": [
            "Yes",
            "No"
          ],
          "values": [
            "true",
            "false"
          ],
          "default": "false"
        }
      ],
      "toggles": []
    }
  ],
  "Tooltip": [
    {
      "name": "Tooltip",
      "figma": "1595:2220",
      "fixed": {},
      "axes": [
        {
          "prop": "color",
          "label": "Color",
          "names": [
            "Default",
            "Accent",
            "White Overlay",
            "Black-Overlay"
          ],
          "values": [
            "default",
            "accent",
            "white-overlay",
            "black-overlay"
          ],
          "default": "default"
        },
        {
          "prop": "size",
          "label": "Size",
          "names": [
            "Medium",
            "Small"
          ],
          "values": [
            "medium",
            "small"
          ],
          "default": "small"
        }
      ],
      "toggles": []
    }
  ],
  "Toast": [
    {
      "name": "Toast-Message",
      "figma": "1579:13276",
      "fixed": {},
      "axes": [
        {
          "prop": "type",
          "label": "Type",
          "names": [
            "Neutral",
            "Subtle",
            "Info",
            "Positive",
            "Warning",
            "Negative"
          ],
          "values": [
            "neutral",
            "subtle",
            "info",
            "positive",
            "warning",
            "negative"
          ],
          "default": "neutral"
        }
      ],
      "toggles": []
    }
  ],
  "FileUpload": [
    {
      "name": "Uploader/File-Upload",
      "figma": "1581:22708",
      "fixed": {},
      "axes": [
        {
          "prop": "type",
          "label": "Type",
          "names": [
            "Drag & Drop",
            "Browse Button"
          ],
          "values": [
            "dropzone",
            "button"
          ],
          "default": "dropzone"
        }
      ],
      "toggles": [
        {
          "prop": "label",
          "label": "hasLabel",
          "on": "Attachments",
          "default": true
        },
        {
          "prop": "helpText",
          "label": "hasHelperText",
          "on": "Up to 5 files.",
          "default": true
        }
      ]
    }
  ],
  "ChatComposer": [
    {
      "name": "Chat-Control",
      "figma": "6182:56819",
      "fixed": {},
      "axes": [
        {
          "prop": "device",
          "label": "Device",
          "names": [
            "Desktop",
            "Mobile"
          ],
          "values": [
            "desktop",
            "mobile"
          ],
          "default": "mobile"
        }
      ],
      "toggles": []
    }
  ],
  "ChatAvatarGroup": [
    {
      "name": "Chat/Avatar-Group",
      "figma": "6340:46191",
      "fixed": {},
      "axes": [
        {
          "prop": "size",
          "label": "Size",
          "names": [
            "Medium",
            "Small"
          ],
          "values": [
            "medium",
            "small"
          ],
          "default": "medium"
        }
      ],
      "toggles": []
    }
  ],
  "AiChatField": [
    {
      "name": "AI/Chat-Field",
      "figma": "12074:16888",
      "fixed": {},
      "axes": [
        {
          "prop": "fieldStyle",
          "label": "Style",
          "names": [
            "Default",
            "Surface",
            "Liquid Glass"
          ],
          "values": [
            "default",
            "surface",
            "liquid-glass"
          ],
          "default": "default"
        }
      ],
      "toggles": []
    }
  ],
  "NumberField": [
    {
      "name": "Input/Number-Align-Left",
      "figma": "421:10057",
      "fixed": {
        "align": "left"
      },
      "axes": [
        {
          "prop": "size",
          "label": "Size",
          "names": [
            "Small",
            "Medium (Base)",
            "Large",
            "XLarge"
          ],
          "values": [
            "small",
            "medium",
            "large",
            "xlarge"
          ],
          "default": "medium"
        },
        {
          "prop": "state",
          "label": "State",
          "names": [
            "Default",
            "Hover",
            "Focused",
            "Typing",
            "Inputted",
            "Read-Only",
            "Disabled",
            "Inputted-Error",
            "Blank-Error"
          ],
          "values": [
            "default",
            "hover",
            "focused",
            "typing",
            "inputted",
            "read-only",
            "disabled",
            "inputted-error",
            "blank-error"
          ],
          "default": "default"
        }
      ],
      "toggles": [
        {
          "prop": "helpText",
          "label": "Help-Text",
          "on": "Help text",
          "default": false
        },
        {
          "prop": "label",
          "label": "Label",
          "on": "Label",
          "default": true
        }
      ]
    },
    {
      "name": "Input/Number-Align-Center",
      "figma": "450:7900",
      "fixed": {
        "align": "center"
      },
      "axes": [
        {
          "prop": "size",
          "label": "Size",
          "names": [
            "Small",
            "Medium (Base)",
            "Large",
            "XLarge"
          ],
          "values": [
            "small",
            "medium",
            "large",
            "xlarge"
          ],
          "default": "medium"
        },
        {
          "prop": "state",
          "label": "State",
          "names": [
            "Default",
            "Hover",
            "Focused",
            "Typing",
            "Inputted",
            "Read-Only",
            "Disabled",
            "Inputted-Error",
            "Blank-Error"
          ],
          "values": [
            "default",
            "hover",
            "focused",
            "typing",
            "inputted",
            "read-only",
            "disabled",
            "inputted-error",
            "blank-error"
          ],
          "default": "default"
        }
      ],
      "toggles": [
        {
          "prop": "helpText",
          "label": "Help-Text",
          "on": "Help text",
          "default": false
        },
        {
          "prop": "label",
          "label": "Label",
          "on": "Label",
          "default": true
        }
      ]
    }
  ],
  "TextAreaField": [
    {
      "name": "Input/Text-Area",
      "figma": "450:7027",
      "fixed": {},
      "axes": [
        {
          "prop": "size",
          "label": "Size",
          "names": [
            "Small",
            "Medium (Base)",
            "Large"
          ],
          "values": [
            "small",
            "medium",
            "large"
          ],
          "default": "medium"
        },
        {
          "prop": "state",
          "label": "State",
          "names": [
            "Default",
            "Hover",
            "Focused",
            "Typing",
            "Inputted",
            "Read-Only",
            "Disabled",
            "Inputted-Error",
            "Blank-Error"
          ],
          "values": [
            "default",
            "hover",
            "focused",
            "typing",
            "inputted",
            "read-only",
            "disabled",
            "inputted-error",
            "blank-error"
          ],
          "default": "default"
        }
      ],
      "toggles": [
        {
          "prop": "helpText",
          "label": "Help-Text",
          "on": "Help text",
          "default": false
        },
        {
          "prop": "label",
          "label": "Label",
          "on": "Label",
          "default": true
        }
      ]
    }
  ],
  "Metric": [
    {
      "name": "Primitives/Metric/Metric-Inline/Icon-Highlight",
      "figma": "595:55188",
      "fixed": {
        "variant": "icon-highlight"
      },
      "axes": [
        {
          "prop": "size",
          "label": "Size",
          "names": [
            "XLarge",
            "Large",
            "Medium",
            "Small",
            "XSmall"
          ],
          "values": [
            "xlarge",
            "large",
            "medium",
            "small",
            "xsmall"
          ],
          "default": "xlarge"
        }
      ],
      "toggles": [
        {
          "prop": "counter",
          "label": "Counter",
          "on": "3",
          "default": false
        }
      ]
    },
    {
      "name": "Primitives/Metric/Metric-Inline/Title-Highlight",
      "figma": "7523:507049",
      "fixed": {
        "variant": "title-highlight"
      },
      "axes": [
        {
          "prop": "size",
          "label": "Size",
          "names": [
            "XLarge",
            "Large",
            "Medium",
            "Small",
            "XSmall"
          ],
          "values": [
            "xlarge",
            "large",
            "medium",
            "small",
            "xsmall"
          ],
          "default": "xlarge"
        }
      ],
      "toggles": [
        {
          "prop": "hint",
          "label": "Hint",
          "on": "How this number is worked out",
          "default": false
        },
        {
          "prop": "labelIcon",
          "label": "Label-Icon",
          "on": "icon-wallet-02-line",
          "default": false
        }
      ]
    }
  ],
  "MetricCard": [
    {
      "name": "Primitives/Metric/Metric-Inline/Icon-Highlight",
      "figma": "595:55188",
      "fixed": {
        "variant": "icon-highlight"
      },
      "axes": [
        {
          "prop": "size",
          "label": "Size",
          "names": [
            "XLarge",
            "Large",
            "Medium",
            "Small",
            "XSmall"
          ],
          "values": [
            "xlarge",
            "large",
            "medium",
            "small",
            "xsmall"
          ],
          "default": "xlarge"
        }
      ],
      "toggles": [
        {
          "prop": "counter",
          "label": "Counter",
          "on": "3",
          "default": false
        }
      ]
    },
    {
      "name": "Primitives/Metric/Metric-Inline/Title-Highlight",
      "figma": "7523:507049",
      "fixed": {
        "variant": "title-highlight"
      },
      "axes": [
        {
          "prop": "size",
          "label": "Size",
          "names": [
            "XLarge",
            "Large",
            "Medium",
            "Small",
            "XSmall"
          ],
          "values": [
            "xlarge",
            "large",
            "medium",
            "small",
            "xsmall"
          ],
          "default": "xlarge"
        }
      ],
      "toggles": [
        {
          "prop": "hint",
          "label": "Hint",
          "on": "How this number is worked out",
          "default": false
        },
        {
          "prop": "labelIcon",
          "label": "Label-Icon",
          "on": "icon-wallet-02-line",
          "default": false
        }
      ]
    }
  ],
  "ChatMessage": [
    {
      "name": "Chat/Conversation/Bubble",
      "figma": "6349:64085",
      "fixed": {},
      "axes": [
        {
          "prop": "side",
          "label": "Side",
          "names": [
            "Others",
            "You"
          ],
          "values": [
            "others",
            "you"
          ],
          "default": "others"
        }
      ],
      "toggles": []
    }
  ],
  "ChatBubble": [
    {
      "name": "Chat/Bubble/Text-You",
      "figma": "6349:59476",
      "fixed": {
        "side": "you"
      },
      "axes": [
        {
          "prop": "domain",
          "label": "Domain",
          "names": [
            "Social",
            "Business"
          ],
          "values": [
            "social",
            "business"
          ],
          "default": "social"
        }
      ],
      "toggles": []
    },
    {
      "name": "Chat/Bubble/Text-Others",
      "figma": "6323:1394",
      "fixed": {
        "side": "others"
      },
      "axes": [
        {
          "prop": "domain",
          "label": "Domain",
          "names": [
            "Social",
            "Business"
          ],
          "values": [
            "social",
            "business"
          ],
          "default": "social"
        }
      ],
      "toggles": []
    }
  ],
  "ChatCall": [
    {
      "name": "Chat/Bubble/Call",
      "figma": "6349:59813",
      "fixed": {},
      "axes": [
        {
          "prop": "type",
          "label": "Type",
          "names": [
            "Audio",
            "Video"
          ],
          "values": [
            "audio",
            "video"
          ],
          "default": "audio"
        },
        {
          "prop": "state",
          "label": "State",
          "names": [
            "In-Call",
            "In-Missed",
            "Out-Call",
            "Out-Missed"
          ],
          "values": [
            "in-call",
            "in-missed",
            "out-call",
            "out-missed"
          ],
          "default": "in-call"
        }
      ],
      "toggles": []
    }
  ],
  "ChatFile": [
    {
      "name": "Chat/Bubble/File",
      "figma": "6182:57708",
      "fixed": {},
      "axes": [
        {
          "prop": "kind",
          "label": "Type",
          "names": [
            "Doc",
            "PDF",
            "Sheet",
            "Others"
          ],
          "values": [
            "doc",
            "pdf",
            "sheet",
            "other"
          ],
          "default": "doc"
        }
      ],
      "toggles": []
    }
  ],
  "ChatConversationItem": [
    {
      "name": "Chat/Conversation-List/List-Item/Content",
      "figma": "6331:34480",
      "fixed": {},
      "axes": [
        {
          "prop": "unread",
          "label": "Unread",
          "names": [
            "No",
            "Yes"
          ],
          "values": [
            "false",
            "true"
          ],
          "default": "true"
        }
      ],
      "toggles": []
    }
  ],
  "AiChatBubble": [
    {
      "name": "AI/Chat-Bubble",
      "figma": "4218:1270",
      "fixed": {},
      "axes": [
        {
          "prop": "side",
          "label": "Side",
          "names": [
            "You",
            "AI"
          ],
          "values": [
            "you",
            "ai"
          ],
          "default": "you"
        }
      ],
      "toggles": []
    }
  ],
  "InputConditionItem": [
    {
      "name": "Primitives/Input/Input-Conditions/Condition-Item",
      "figma": "373:97437",
      "fixed": {},
      "axes": [
        {
          "prop": "state",
          "label": "State",
          "names": [
            "Default",
            "Success",
            "Wrong"
          ],
          "values": [
            "default",
            "success",
            "wrong"
          ],
          "default": "default"
        }
      ],
      "toggles": []
    }
  ],
  "ControlBarSelectItem": [
    {
      "name": "Control-Bar/Select-Item",
      "figma": "9021:27379",
      "fixed": {},
      "axes": [
        {
          "prop": "theme",
          "label": "Theme",
          "names": [
            "Subtle",
            "Solid",
            "Inverse"
          ],
          "values": [
            "subtle",
            "solid",
            "inverse"
          ],
          "default": "subtle"
        },
        {
          "prop": "state",
          "label": "State",
          "names": [
            "Default",
            "Hover",
            "Selected"
          ],
          "values": [
            "default",
            "hover",
            "selected"
          ],
          "default": "default"
        }
      ],
      "toggles": []
    }
  ]
};
