// Handoff rows (Studio builder GĐ5, spec docs/research/studio-builder-handoff-spec-2026-10-07.md): a builder page
// exported as React code (tools/studio/compile.mjs) or as its design file, from the Export panel.
import { sleep, until } from "../lib/studio.mjs";
import { newPage, pageText } from "./builder.mjs";

/** Opens the Export panel from the page's Inspector panel (nothing selected). */
async function openExport(page) {
  await page.locator(".studio-viewport").focus();
  for (let i = 0; i < 3; i += 1) await page.keyboard.press("Escape");
  await page.locator("#studio-right").getByRole("tab", { name: "Design" }).click().catch(() => {});
  await page.locator("#studio-right").getByRole("button", { name: "Export…" }).click();
  const panel = page.locator(".studio-export");
  await panel.waitFor({ state: "visible", timeout: 5000 });
  return panel;
}
const clipboard = (page) => page.evaluate(() => navigator.clipboard.readText());

export const rows = [
  {
    id: "HO-01", feature: "Export a page as React: the component's code, Copy; the Design file tab shows the page itself", wp: "GĐ5 M1",
    async run(ctx) {
      const { page, id } = await newPage(ctx, { title: "Export check" });
      const panel = await openExport(page);
      await until(async () => /export function ExportCheckPage\(/.test(await panel.innerText()), { message: "the React code in the panel" });
      await panel.getByRole("button", { name: "Copy code" }).click();
      const react = await until(async () => { const text = await clipboard(page); return /Generated by Zen Studio from/.test(text) ? text : null; }, { message: "the React code copied" });
      if (!/import \{ Stack, Text \} from "@zen\/design-system";/.test(react)) throw new Error(`unexpected code:\n${react.slice(0, 400)}`);
      await panel.getByRole("button", { name: "Design file" }).click();
      await panel.getByRole("button", { name: "Copy code" }).click();
      const design = await until(async () => { const text = await clipboard(page); return text.startsWith("// @zen-page") ? text : null; }, { message: "the design file copied" });
      if (design !== (await pageText(page, id))) throw new Error("the design file differs from the stored page");
      await page.keyboard.press("Escape");
      await sleep(200);
      return `ExportCheckPage (${react.split("\n").length} lines) copied; design file = the stored page`;
    },
  },
];
