// Generated by tools/studio/figma-props-build.mjs from docs/figma-contracts/component-properties.json (Figma 9nZv4uW2LT21yuHabMTCh1,
// read 2026-10-05) and tools/studio/figma-props.map.mjs. Do not edit: change the map and run the script.

/** A component's Figma properties for the Studio's Properties panel (inspector/propGroups.ts). */
export type FigmaPropsEntry = {
  /** The Figma component set the order and names follow (the first of its sets). */
  figma: string;
  /** Its properties in Figma order: the code prop, the Figma name and property type ("SET": which of its Figma sets),
   *  and Figma option name → code value. */
  own: ReadonlyArray<{ prop: string; label?: string; type: string; options?: Readonly<Record<string, string>> }>;
  /** Figma booleans that show a layer: on writes `on` (a text; "slot": the content-slot picker; { code }: an object or a
   *  list written as code), off removes the prop. */
  toggles: ReadonlyArray<{ label: string; prop: string; on: string | { code: string } }>;
  /** Nested layers (an Input's Label): shown while `when` is set, with their properties ("CODE": a code prop the
   *  nested Figma set has no property for, labelled here). */
  nested?: ReadonlyArray<{ name: string; figma?: string; when: string; own: ReadonlyArray<{ prop: string; label?: string; type: string }> }>;
};

export const FIGMA_PROPS: Readonly<Record<string, FigmaPropsEntry>> = {
  "Button": {
    "figma": "1026:8312",
    "own": [
      {
        "prop": "appearance",
        "type": "SET",
        "options": {
          "Button/Main": "main",
          "Button/Flat": "flat",
          "Button/Overlay": "overlay"
        }
      },
      {
        "prop": "startIcon",
        "label": "Leading-Icon-Src",
        "type": "INSTANCE_SWAP"
      },
      {
        "prop": "endIcon",
        "label": "Trailing-Icon-Src",
        "type": "INSTANCE_SWAP"
      },
      {
        "prop": "size",
        "label": "Size",
        "type": "VARIANT",
        "options": {
          "XLarge": "xlarge",
          "Large": "large",
          "Medium (Base)": "medium",
          "Small": "small",
          "XSmall": "xsmall"
        }
      },
      {
        "prop": "level",
        "label": "Level",
        "type": "VARIANT",
        "options": {
          "Primary": "primary",
          "Accent": "accent",
          "Secondary": "secondary",
          "Tertiary": "tertiary",
          "Danger": "danger",
          "Danger Subtle": "danger-subtle",
          "Positive": "positive",
          "Positive Subtle": "positive-subtle",
          "Surface": "surface",
          "Inverse": "inverse",
          "White": "white",
          "White Overlay": "white-overlay",
          "Black Overlay": "black-overlay"
        }
      },
      {
        "prop": "state",
        "label": "State",
        "type": "VARIANT",
        "options": {
          "Default": "default",
          "Hover": "hover",
          "Pressed": "pressed",
          "Focused": "focused",
          "Disabled": "disabled"
        }
      }
    ],
    "toggles": [
      {
        "label": "Leading-Icon",
        "prop": "startIcon",
        "on": "icon-check-line"
      },
      {
        "label": "Trailing-Icon",
        "prop": "endIcon",
        "on": "icon-chevron-right-line-small"
      }
    ]
  },
  "IconButton": {
    "figma": "205:21062",
    "own": [
      {
        "prop": "appearance",
        "type": "SET",
        "options": {
          "Button/Icon-Main": "main",
          "Button/Icon-Flat": "flat",
          "Button/Icon-Overlay": "overlay"
        }
      },
      {
        "prop": "icon",
        "label": "Leading-Icon-Src",
        "type": "INSTANCE_SWAP"
      },
      {
        "prop": "size",
        "label": "Size",
        "type": "VARIANT",
        "options": {
          "XLarge": "xlarge",
          "Large": "large",
          "Medium": "medium",
          "Small": "small",
          "XSmall": "xsmall",
          "2XSmall": "2xsmall"
        }
      },
      {
        "prop": "level",
        "label": "Level",
        "type": "VARIANT",
        "options": {
          "Primary": "primary",
          "Accent": "accent",
          "Secondary": "secondary",
          "Tertiary": "tertiary",
          "Danger": "danger",
          "Danger Secondary": "danger-secondary",
          "Positive": "positive",
          "Positive Secondary": "positive-secondary",
          "Surface": "surface",
          "Inverse": "inverse",
          "White": "white",
          "White Overlay": "white-overlay",
          "Black Overlay": "black-overlay"
        }
      },
      {
        "prop": "state",
        "label": "State",
        "type": "VARIANT",
        "options": {
          "Default": "default",
          "Hover": "hover",
          "Pressed": "pressed",
          "Focused": "focused",
          "Disabled": "disabled"
        }
      }
    ],
    "toggles": []
  },
  "Avatar": {
    "figma": "223:9050",
    "own": [
      {
        "prop": "status",
        "label": "Status",
        "type": "BOOLEAN"
      },
      {
        "prop": "focus",
        "label": "Focus",
        "type": "BOOLEAN"
      },
      {
        "prop": "shape",
        "label": "Shape",
        "type": "VARIANT",
        "options": {
          "Circle": "circle",
          "Square": "square"
        }
      },
      {
        "prop": "size",
        "label": "Size",
        "type": "VARIANT",
        "options": {
          "3XLarge": "3xlarge",
          "2XLarge": "2xlarge",
          "XLarge": "xlarge",
          "Large": "large",
          "Medium": "medium",
          "Small": "small",
          "XSmall": "xsmall",
          "2XSmall": "2xsmall"
        }
      },
      {
        "prop": "theme",
        "label": "Theme",
        "type": "VARIANT",
        "options": {
          "Photo": "photo",
          "Accent": "accent",
          "Blue": "blue",
          "Brown": "brown",
          "Crimson": "crimson",
          "Cyan": "cyan",
          "Green": "green",
          "Indigo": "indigo",
          "Neutral": "neutral",
          "Orange": "orange",
          "Pink": "pink",
          "Plum": "plum",
          "Purple": "purple",
          "Red": "red",
          "Teal": "teal",
          "Violet": "violet",
          "Yellow": "yellow"
        }
      },
      {
        "prop": "background",
        "label": "Background",
        "type": "VARIANT",
        "options": {
          "Solid": "solid",
          "Subtle": "subtle"
        }
      }
    ],
    "toggles": []
  },
  "AvatarStack": {
    "figma": "364:92561",
    "own": [
      {
        "prop": "showMore",
        "label": "More",
        "type": "BOOLEAN"
      },
      {
        "prop": "size",
        "label": "Size",
        "type": "VARIANT",
        "options": {
          "Medium": "medium",
          "Small": "small"
        }
      },
      {
        "prop": "background",
        "label": "Background",
        "type": "VARIANT",
        "options": {
          "Subtle": "subtle",
          "Solid": "solid"
        }
      }
    ],
    "toggles": []
  },
  "Accordion": {
    "figma": "239:16847",
    "own": [
      {
        "prop": "size",
        "label": "Size",
        "type": "VARIANT",
        "options": {
          "XLarge": "xlarge",
          "Large": "large",
          "Medium": "medium"
        }
      },
      {
        "prop": "theme",
        "label": "Theme",
        "type": "VARIANT",
        "options": {
          "Divider": "divider",
          "Box": "box"
        }
      },
      {
        "prop": "expanded",
        "label": "Expanded",
        "type": "VARIANT",
        "options": {
          "No": "false",
          "Yes": "true"
        }
      },
      {
        "prop": "contentWidth",
        "label": "Content Width",
        "type": "VARIANT",
        "options": {
          "Title": "title",
          "Full": "full"
        }
      }
    ],
    "toggles": []
  },
  "AlertBanner": {
    "figma": "6828:9393",
    "own": [
      {
        "prop": "leading",
        "label": "Leading",
        "type": "BOOLEAN"
      },
      {
        "prop": "size",
        "label": "Size",
        "type": "VARIANT",
        "options": {
          "Medium": "medium",
          "Small": "small"
        }
      },
      {
        "prop": "theme",
        "label": "Theme",
        "type": "VARIANT",
        "options": {
          "Default": "default",
          "Info": "info",
          "Positive": "positive",
          "Warning": "warning",
          "Negative": "negative"
        }
      }
    ],
    "toggles": [
      {
        "label": "Action",
        "prop": "action",
        "on": {
          "code": "{ label: \"Action\" }"
        }
      }
    ]
  },
  "Badge": {
    "figma": "260:4825",
    "own": [
      {
        "prop": "remove",
        "label": "Remove",
        "type": "BOOLEAN"
      },
      {
        "prop": "leadingIcon",
        "label": "Leading-Icon",
        "type": "BOOLEAN"
      },
      {
        "prop": "leading",
        "label": "Leading-Icon-Src",
        "type": "INSTANCE_SWAP"
      },
      {
        "prop": "size",
        "label": "Size",
        "type": "VARIANT",
        "options": {
          "Medium": "medium",
          "Small": "small",
          "XSmall": "xsmall"
        }
      },
      {
        "prop": "theme",
        "label": "Theme",
        "type": "VARIANT",
        "options": {
          "Accent": "accent",
          "Neutral": "neutral",
          "Yellow": "yellow",
          "Orange": "orange",
          "Red": "red",
          "Crimson": "crimson",
          "Pink": "pink",
          "Plum": "plum",
          "Purple": "purple",
          "Violet": "violet",
          "Indigo": "indigo",
          "Blue": "blue",
          "Cyan": "cyan",
          "Teal": "teal",
          "Green": "green",
          "Brown": "brown",
          "Inverse": "inverse",
          "On-Color": "on-color"
        }
      },
      {
        "prop": "background",
        "label": "Background",
        "type": "VARIANT",
        "options": {
          "Solid": "solid",
          "Subtle": "subtle"
        }
      }
    ],
    "toggles": []
  },
  "BadgeCounter": {
    "figma": "9535:33812",
    "own": [
      {
        "prop": "value",
        "label": "Text",
        "type": "TEXT"
      },
      {
        "prop": "size",
        "label": "Size",
        "type": "VARIANT",
        "options": {
          "Medium": "medium",
          "Small": "small",
          "XSmall": "xsmall"
        }
      },
      {
        "prop": "theme",
        "label": "Theme",
        "type": "VARIANT",
        "options": {
          "Accent": "accent",
          "Neutral": "neutral",
          "Yellow": "yellow",
          "Orange": "orange",
          "Red": "red",
          "Crimson": "crimson",
          "Pink": "pink",
          "Plum": "plum",
          "Purple": "purple",
          "Violet": "violet",
          "Indigo": "indigo",
          "Blue": "blue",
          "Cyan": "cyan",
          "Teal": "teal",
          "Green": "green",
          "Brown": "brown",
          "Inverse": "inverse",
          "On-Color": "on-color"
        }
      },
      {
        "prop": "background",
        "label": "Background",
        "type": "VARIANT",
        "options": {
          "Solid": "solid",
          "Subtle": "subtle"
        }
      }
    ],
    "toggles": []
  },
  "BottomSheet": {
    "figma": "4059:14161",
    "own": [
      {
        "prop": "type",
        "label": "Type",
        "type": "VARIANT",
        "options": {
          "Modal": "modal",
          "Action": "action"
        }
      },
      {
        "prop": "size",
        "label": "Size",
        "type": "VARIANT",
        "options": {
          "Flex": "flex",
          "Max-Fixed": "max"
        }
      }
    ],
    "toggles": [
      {
        "label": "Header",
        "prop": "title",
        "on": "Title"
      }
    ]
  },
  "Card": {
    "figma": "6643:51021",
    "own": [
      {
        "prop": "theme",
        "label": "Theme",
        "type": "VARIANT",
        "options": {
          "Shadow": "shadow",
          "Flat": "flat",
          "Pale": "pale",
          "Border": "border",
          "Semi-Pale": "semi-pale"
        }
      },
      {
        "prop": "spacing",
        "label": "Spacing",
        "type": "VARIANT",
        "options": {
          "Medium": "medium",
          "Small": "small"
        }
      },
      {
        "prop": "active",
        "label": "Active",
        "type": "VARIANT",
        "options": {
          "No": "false",
          "Yes": "true"
        }
      }
    ],
    "toggles": []
  },
  "Chip": {
    "figma": "512:6843",
    "own": [
      {
        "prop": "variant",
        "type": "SET",
        "options": {
          "Chip/Normal": "normal",
          "Chip/Advanced": "advanced",
          "Chip/Number-Only": "number-only"
        }
      },
      {
        "prop": "leading",
        "label": "Icon-Src",
        "type": "INSTANCE_SWAP"
      },
      {
        "prop": "size",
        "label": "Size",
        "type": "VARIANT",
        "options": {
          "Medium": "medium",
          "Small": "small",
          "XSmall": "xsmall"
        }
      },
      {
        "prop": "level",
        "label": "Level",
        "type": "VARIANT",
        "options": {
          "Primary": "primary",
          "Secondary": "secondary"
        }
      },
      {
        "prop": "theme",
        "label": "Theme",
        "type": "VARIANT",
        "options": {
          "Text-Only": "text-only",
          "Leading-Icon": "leading-icon",
          "Leading-Photo": "leading-photo"
        }
      },
      {
        "prop": "state",
        "label": "State",
        "type": "VARIANT",
        "options": {
          "Default": "default",
          "Hover": "hover",
          "Focused": "focused",
          "Press": "press",
          "Placeholder": "placeholder"
        }
      },
      {
        "prop": "selected",
        "label": "Select",
        "type": "VARIANT",
        "options": {
          "No": "false",
          "Yes": "true"
        }
      }
    ],
    "toggles": []
  },
  "Checkbox": {
    "figma": "309:46871",
    "own": [
      {
        "prop": "state",
        "label": "State",
        "type": "VARIANT",
        "options": {
          "Default": "default",
          "Hover": "hover",
          "Focus": "focus",
          "Disabled": "disabled"
        }
      },
      {
        "prop": "checked",
        "label": "Select",
        "type": "VARIANT",
        "options": {
          "No": "false",
          "Yes": "true"
        }
      },
      {
        "prop": "checkSide",
        "label": "Check-Side",
        "type": "VARIANT",
        "options": {
          "Left": "left",
          "Right": "right"
        }
      }
    ],
    "toggles": [
      {
        "label": "Caption",
        "prop": "caption",
        "on": "Caption"
      }
    ]
  },
  "Divider": {
    "figma": "460:38361",
    "own": [
      {
        "prop": "color",
        "label": "Color",
        "type": "VARIANT",
        "options": {
          "Default": "default",
          "Medium": "medium",
          "High": "high"
        }
      }
    ],
    "toggles": []
  },
  "DockIcon": {
    "figma": "308:45902",
    "own": [
      {
        "prop": "icon",
        "label": "Icon-Src",
        "type": "INSTANCE_SWAP"
      },
      {
        "prop": "size",
        "label": "Size",
        "type": "VARIANT",
        "options": {
          "XLarge": "xlarge",
          "Large": "large",
          "Medium": "medium",
          "Small": "small",
          "XSmall": "xsmall"
        }
      },
      {
        "prop": "theme",
        "label": "Theme",
        "type": "VARIANT",
        "options": {
          "Accent": "accent",
          "Blue": "blue",
          "Brown": "brown",
          "Crimson": "crimson",
          "Cyan": "cyan",
          "Green": "green",
          "Indigo": "indigo",
          "Neutral": "neutral",
          "Orange": "orange",
          "Pink": "pink",
          "Plum": "plum",
          "Purple": "purple",
          "Red": "red",
          "Teal": "teal",
          "Violet": "violet",
          "Yellow": "yellow",
          "On-Color": "on-color",
          "Emoji": "emoji",
          "Golden": "golden",
          "Inverse": "inverse",
          "Pale": "pale",
          "Surface": "surface"
        }
      },
      {
        "prop": "background",
        "label": "Background",
        "type": "VARIANT",
        "options": {
          "Solid": "solid",
          "Subtle": "subtle"
        }
      }
    ],
    "toggles": []
  },
  "DescriptionList": {
    "figma": "14859:79180",
    "own": [
      {
        "prop": "layout",
        "label": "Layout",
        "type": "VARIANT",
        "options": {
          "Inline": "inline",
          "Stacked": "stacked"
        }
      },
      {
        "prop": "divider",
        "label": "Divider",
        "type": "VARIANT",
        "options": {
          "No": "false",
          "Yes": "true"
        }
      }
    ],
    "toggles": []
  },
  "InputField": {
    "figma": "421:4108",
    "own": [
      {
        "prop": "size",
        "label": "Size",
        "type": "VARIANT",
        "options": {
          "Small": "small",
          "Medium (Base)": "medium",
          "Large": "large",
          "XLarge": "xlarge"
        }
      },
      {
        "prop": "state",
        "label": "State",
        "type": "VARIANT",
        "options": {
          "Default": "default",
          "Hover": "hover",
          "Focused": "focused",
          "Typing": "typing",
          "Inputted": "inputted",
          "Read-Only": "read-only",
          "Disabled": "disabled",
          "Inputted-Error": "inputted-error",
          "Blank-Error": "blank-error"
        }
      }
    ],
    "toggles": [
      {
        "label": "Help-Text",
        "prop": "helpText",
        "on": "Help text"
      },
      {
        "label": "Label",
        "prop": "label",
        "on": "Label"
      }
    ],
    "nested": [
      {
        "name": "Label",
        "figma": "387:3651",
        "when": "label",
        "own": [
          {
            "prop": "labelOptional",
            "label": "Optional",
            "type": "BOOLEAN"
          },
          {
            "prop": "labelTooltip",
            "label": "Tooltip-Icon",
            "type": "BOOLEAN"
          },
          {
            "prop": "labelAction",
            "label": "Action",
            "type": "BOOLEAN"
          },
          {
            "prop": "label",
            "label": "Label",
            "type": "TEXT"
          }
        ]
      },
      {
        "name": "Help-Text",
        "when": "helpText",
        "own": [
          {
            "prop": "helpText",
            "label": "Text",
            "type": "CODE"
          },
          {
            "prop": "helpTheme",
            "label": "Theme",
            "type": "CODE"
          },
          {
            "prop": "helpIcon",
            "label": "Icon",
            "type": "CODE"
          },
          {
            "prop": "characterLimit",
            "label": "Character limit",
            "type": "CODE"
          }
        ]
      }
    ]
  },
  "SelectField": {
    "figma": "421:7303",
    "own": [
      {
        "prop": "size",
        "label": "Size",
        "type": "VARIANT",
        "options": {
          "Small": "small",
          "Medium (Base)": "medium",
          "Large": "large",
          "XLarge": "xlarge"
        }
      },
      {
        "prop": "state",
        "label": "State",
        "type": "VARIANT",
        "options": {
          "Default": "default",
          "Hover": "hover",
          "Focused": "focused",
          "Typing": "typing",
          "Inputted": "inputted",
          "Read-Only": "read-only",
          "Disabled": "disabled",
          "Inputted-Error": "inputted-error",
          "Blank-Error": "blank-error"
        }
      }
    ],
    "toggles": [
      {
        "label": "Help-Text",
        "prop": "helpText",
        "on": "Help text"
      },
      {
        "label": "Label",
        "prop": "label",
        "on": "Label"
      }
    ],
    "nested": [
      {
        "name": "Label",
        "figma": "387:3651",
        "when": "label",
        "own": [
          {
            "prop": "labelOptional",
            "label": "Optional",
            "type": "BOOLEAN"
          },
          {
            "prop": "labelTooltip",
            "label": "Tooltip-Icon",
            "type": "BOOLEAN"
          },
          {
            "prop": "labelAction",
            "label": "Action",
            "type": "BOOLEAN"
          },
          {
            "prop": "label",
            "label": "Label",
            "type": "TEXT"
          }
        ]
      },
      {
        "name": "Help-Text",
        "when": "helpText",
        "own": [
          {
            "prop": "helpText",
            "label": "Text",
            "type": "CODE"
          },
          {
            "prop": "helpTheme",
            "label": "Theme",
            "type": "CODE"
          },
          {
            "prop": "helpIcon",
            "label": "Icon",
            "type": "CODE"
          },
          {
            "prop": "characterLimit",
            "label": "Character limit",
            "type": "CODE"
          }
        ]
      }
    ]
  },
  "DateField": {
    "figma": "421:8388",
    "own": [
      {
        "prop": "size",
        "label": "Size",
        "type": "VARIANT",
        "options": {
          "Small": "small",
          "Medium (Base)": "medium",
          "Large": "large",
          "XLarge": "xlarge"
        }
      },
      {
        "prop": "state",
        "label": "State",
        "type": "VARIANT",
        "options": {
          "Default": "default",
          "Hover": "hover",
          "Focused": "focused",
          "Typing": "typing",
          "Inputted": "inputted",
          "Read-Only": "read-only",
          "Disabled": "disabled",
          "Inputted-Error": "inputted-error",
          "Blank-Error": "blank-error"
        }
      }
    ],
    "toggles": [
      {
        "label": "Help-Text",
        "prop": "helpText",
        "on": "Help text"
      },
      {
        "label": "Label",
        "prop": "label",
        "on": "Label"
      }
    ],
    "nested": [
      {
        "name": "Label",
        "figma": "387:3651",
        "when": "label",
        "own": [
          {
            "prop": "labelOptional",
            "label": "Optional",
            "type": "BOOLEAN"
          },
          {
            "prop": "labelTooltip",
            "label": "Tooltip-Icon",
            "type": "BOOLEAN"
          },
          {
            "prop": "labelAction",
            "label": "Action",
            "type": "BOOLEAN"
          },
          {
            "prop": "label",
            "label": "Label",
            "type": "TEXT"
          }
        ]
      },
      {
        "name": "Help-Text",
        "when": "helpText",
        "own": [
          {
            "prop": "helpText",
            "label": "Text",
            "type": "CODE"
          },
          {
            "prop": "helpTheme",
            "label": "Theme",
            "type": "CODE"
          },
          {
            "prop": "helpIcon",
            "label": "Icon",
            "type": "CODE"
          },
          {
            "prop": "characterLimit",
            "label": "Character limit",
            "type": "CODE"
          }
        ]
      }
    ]
  },
  "AutocompleteField": {
    "figma": "1241:5616",
    "own": [],
    "toggles": [
      {
        "label": "Help-Text",
        "prop": "helpText",
        "on": "Help text"
      }
    ],
    "nested": [
      {
        "name": "Help-Text",
        "when": "helpText",
        "own": [
          {
            "prop": "helpText",
            "label": "Text",
            "type": "CODE"
          },
          {
            "prop": "helpTheme",
            "label": "Theme",
            "type": "CODE"
          },
          {
            "prop": "helpIcon",
            "label": "Icon",
            "type": "CODE"
          }
        ]
      }
    ]
  },
  "RichTextField": {
    "figma": "6385:17480",
    "own": [
      {
        "prop": "editorBar",
        "label": "Control-Bar",
        "type": "BOOLEAN"
      }
    ],
    "toggles": []
  },
  "HeadingField": {
    "figma": "694:13062",
    "own": [
      {
        "prop": "status",
        "label": "Status",
        "type": "VARIANT",
        "options": {
          "Default": "default",
          "Hover": "hover",
          "Focus": "focus",
          "Typing": "typing",
          "Inputted-Single-Line": "inputted-single-line",
          "Inputted-Multi-Line": "inputted-multi-line",
          "Inputted-Hover": "inputted-hover"
        }
      },
      {
        "prop": "headingSize",
        "label": "Size",
        "type": "VARIANT",
        "options": {
          "H1": "h1",
          "H2": "h2",
          "H3": "h3"
        }
      }
    ],
    "toggles": []
  },
  "InlineMessage": {
    "figma": "595:54857",
    "own": [
      {
        "prop": "theme",
        "label": "Theme",
        "type": "VARIANT",
        "options": {
          "Neutral": "neutral",
          "Info": "info",
          "Warning": "warning",
          "Negative": "negative",
          "Custom": "custom"
        }
      }
    ],
    "toggles": [
      {
        "label": "Action",
        "prop": "action",
        "on": {
          "code": "{ label: \"Action\" }"
        }
      },
      {
        "label": "Title",
        "prop": "title",
        "on": "Title"
      }
    ]
  },
  "ListItem": {
    "figma": "4080:11700",
    "own": [],
    "toggles": [
      {
        "label": "Trailing",
        "prop": "trailing",
        "on": "slot"
      },
      {
        "label": "Leading",
        "prop": "leading",
        "on": "slot"
      }
    ]
  },
  "ListBox": {
    "figma": "14922:75297",
    "own": [],
    "toggles": [
      {
        "label": "Header",
        "prop": "header",
        "on": "slot"
      },
      {
        "label": "Footer",
        "prop": "footer",
        "on": "slot"
      }
    ]
  },
  "Dialog": {
    "figma": "841:17177",
    "own": [
      {
        "prop": "icon",
        "label": "Modal-Icon",
        "type": "BOOLEAN"
      },
      {
        "prop": "theme",
        "label": "Theme",
        "type": "VARIANT",
        "options": {
          "Default": "default",
          "Info": "info",
          "Positive": "positive",
          "Warning": "warning",
          "Negative": "negative"
        }
      }
    ],
    "toggles": [
      {
        "label": "Caption",
        "prop": "description",
        "on": "Description"
      }
    ]
  },
  "ModalForm": {
    "figma": "841:17182",
    "own": [
      {
        "prop": "closeButton",
        "label": "Close",
        "type": "BOOLEAN"
      },
      {
        "prop": "header",
        "label": "Default-Header",
        "type": "BOOLEAN"
      },
      {
        "prop": "layout",
        "label": "Layout",
        "type": "VARIANT",
        "options": {
          "Basic": "basic",
          "1-3": "1-3",
          "Half-Half": "half-half",
          "3-4": "3-4",
          "Big": "big"
        }
      }
    ],
    "toggles": [
      {
        "label": "Caption",
        "prop": "description",
        "on": "Description"
      }
    ]
  },
  "Popover": {
    "figma": "4031:26126",
    "own": [
      {
        "prop": "search",
        "label": "Search",
        "type": "BOOLEAN"
      },
      {
        "prop": "scrollBar",
        "label": "Scroll-Bar",
        "type": "BOOLEAN"
      }
    ],
    "toggles": [
      {
        "label": "Label",
        "prop": "label",
        "on": "Label"
      }
    ]
  },
  "ProgressBar": {
    "figma": "1536:260",
    "own": [
      {
        "prop": "theme",
        "label": "Theme",
        "type": "VARIANT",
        "options": {
          "Accent": "accent",
          "Neutral": "neutral",
          "Status": "status"
        }
      }
    ],
    "toggles": [
      {
        "label": "Label",
        "prop": "label",
        "on": "Label"
      }
    ]
  },
  "ProgressCircle": {
    "figma": "1531:13954",
    "own": [],
    "toggles": [
      {
        "label": "Label",
        "prop": "label",
        "on": "Label"
      }
    ]
  },
  "Pagination": {
    "figma": "774:29083",
    "own": [
      {
        "prop": "theme",
        "label": "Theme",
        "type": "VARIANT",
        "options": {
          "Primary": "primary",
          "Secondary": "secondary",
          "Inline": "inline",
          "Manually": "manually"
        }
      }
    ],
    "toggles": []
  },
  "Rating": {
    "figma": "1536:26008",
    "own": [
      {
        "prop": "size",
        "label": "Size",
        "type": "VARIANT",
        "options": {
          "XSmall": "xsmall",
          "Small": "small",
          "Medium": "medium",
          "Large": "large",
          "XLarge": "xlarge"
        }
      },
      {
        "prop": "theme",
        "label": "Theme",
        "type": "VARIANT",
        "options": {
          "Default": "default",
          "Neutral": "neutral",
          "Accent": "accent"
        }
      }
    ],
    "toggles": []
  },
  "RatingDisplay": {
    "figma": "9818:5582",
    "own": [
      {
        "prop": "size",
        "label": "Size",
        "type": "VARIANT",
        "options": {
          "XLarge": "xlarge",
          "Large": "large",
          "Medium": "medium",
          "Small": "small",
          "XSmall": "xsmall"
        }
      },
      {
        "prop": "theme",
        "label": "Theme",
        "type": "VARIANT",
        "options": {
          "Neutral": "neutral",
          "Default": "default",
          "Accent": "accent"
        }
      }
    ],
    "toggles": []
  },
  "OpinionScale": {
    "figma": "1536:25762",
    "own": [
      {
        "prop": "scale",
        "label": "Scale",
        "type": "VARIANT",
        "options": {
          "2": "2",
          "3": "3",
          "5": "5"
        }
      }
    ],
    "toggles": []
  },
  "NpsScale": {
    "figma": "1536:26034",
    "own": [
      {
        "prop": "highLabel",
        "label": "Top criteria",
        "type": "TEXT"
      },
      {
        "prop": "lowLabel",
        "label": "Bottom criteria",
        "type": "TEXT"
      },
      {
        "prop": "scale",
        "label": "Scale",
        "type": "VARIANT",
        "options": {
          "5": "5",
          "10": "10"
        }
      }
    ],
    "toggles": []
  },
  "RadioButton": {
    "figma": "373:96272",
    "own": [
      {
        "prop": "state",
        "label": "State",
        "type": "VARIANT",
        "options": {
          "Default": "default",
          "Hover": "hover",
          "Focus": "focus",
          "Disabled": "disabled"
        }
      },
      {
        "prop": "checked",
        "label": "Select",
        "type": "VARIANT",
        "options": {
          "No": "false",
          "Yes": "true"
        }
      },
      {
        "prop": "radioSide",
        "label": "Radio-Side",
        "type": "VARIANT",
        "options": {
          "Left": "left",
          "Right": "right"
        }
      }
    ],
    "toggles": []
  },
  "Search": {
    "figma": "846:37624",
    "own": [
      {
        "prop": "variant",
        "type": "SET",
        "options": {
          "Search/Default": "default",
          "Search/Popover": "popover"
        }
      },
      {
        "prop": "size",
        "label": "Size",
        "type": "VARIANT",
        "options": {
          "Medium": "medium",
          "Small": "small"
        }
      },
      {
        "prop": "theme",
        "label": "Theme",
        "type": "VARIANT",
        "options": {
          "Default": "default",
          "Filter-Icon": "filter-icon",
          "Filter-Dropdown": "filter-dropdown"
        }
      },
      {
        "prop": "state",
        "label": "State",
        "type": "VARIANT",
        "options": {
          "Default": "default",
          "Hover": "hover",
          "Focused": "focused",
          "Typing": "typing",
          "Inputted": "inputted"
        }
      },
      {
        "prop": "iconSearch",
        "label": "Icon-Search",
        "type": "VARIANT",
        "options": {
          "Yes": "true",
          "No": "false"
        }
      }
    ],
    "toggles": []
  },
  "Slider": {
    "figma": "4010:35946",
    "own": [
      {
        "prop": "icon",
        "label": "Icon-Src",
        "type": "INSTANCE_SWAP"
      },
      {
        "prop": "theme",
        "label": "Theme",
        "type": "VARIANT",
        "options": {
          "Neutral": "neutral",
          "Accent": "accent",
          "White": "white"
        }
      },
      {
        "prop": "size",
        "label": "Size",
        "type": "VARIANT",
        "options": {
          "Small": "small",
          "Medium": "medium",
          "Large": "large"
        }
      }
    ],
    "toggles": [
      {
        "label": "Icon",
        "prop": "icon",
        "on": "icon-volume-max-line"
      }
    ]
  },
  "Sidebar": {
    "figma": "4081:15234",
    "own": [
      {
        "prop": "variant",
        "type": "SET",
        "options": {
          "Side-Bar/Master/Basic": "basic",
          "Side-Bar/Master/Workspace": "workspace",
          "Side-Bar/Master/Small-Density": "small-density"
        }
      },
      {
        "prop": "workspaceBar",
        "label": "Workspace-bar",
        "type": "BOOLEAN"
      },
      {
        "prop": "background",
        "label": "Master-Background",
        "type": "VARIANT",
        "options": {
          "Flat": "flat",
          "Default": "default",
          "Inverse": "inverse"
        }
      }
    ],
    "toggles": []
  },
  "SkeletonText": {
    "figma": "1556:17566",
    "own": [],
    "toggles": []
  },
  "SkeletonHeading": {
    "figma": "1556:17593",
    "own": [
      {
        "prop": "size",
        "label": "Size",
        "type": "VARIANT",
        "options": {
          "Large": "large",
          "Medium": "medium",
          "Small": "small"
        }
      }
    ],
    "toggles": []
  },
  "SkeletonShape": {
    "figma": "1556:17525",
    "own": [
      {
        "prop": "shape",
        "label": "Shape",
        "type": "VARIANT",
        "options": {
          "Pill": "pill",
          "Round": "round",
          "Square": "square",
          "Rectangle": "rectangle"
        }
      },
      {
        "prop": "size",
        "label": "Size",
        "type": "VARIANT",
        "options": {
          "Large - 48px": "large",
          "Medium - 40px": "medium",
          "Small - 32px": "small",
          "XSmall": "xsmall",
          "2XSmall": "2xsmall"
        }
      }
    ],
    "toggles": []
  },
  "Segmented": {
    "figma": "1238:892",
    "own": [
      {
        "prop": "level",
        "label": "Level",
        "type": "VARIANT",
        "options": {
          "Secondary": "secondary",
          "Primary": "primary"
        }
      }
    ],
    "toggles": []
  },
  "SidePanel": {
    "figma": "1573:3128",
    "own": [
      {
        "prop": "type",
        "label": "Type",
        "type": "VARIANT",
        "options": {
          "Modal": "modal",
          "Standard": "standard"
        }
      },
      {
        "prop": "size",
        "label": "Size",
        "type": "VARIANT",
        "options": {
          "Default": "default",
          "Small": "small"
        }
      }
    ],
    "toggles": []
  },
  "Tabs": {
    "figma": "1577:5477",
    "own": [
      {
        "prop": "variant",
        "label": "Style",
        "type": "VARIANT",
        "options": {
          "Indicator": "indicator",
          "Subtle": "subtle"
        }
      }
    ],
    "toggles": []
  },
  "Tag": {
    "figma": "288:32046",
    "own": [
      {
        "prop": "leading",
        "label": "Icon-Src",
        "type": "INSTANCE_SWAP"
      },
      {
        "prop": "state",
        "label": "State",
        "type": "VARIANT",
        "options": {
          "Default": "default",
          "Hover": "hover",
          "Focused": "focused",
          "Error": "error",
          "Disabled": "disabled"
        }
      },
      {
        "prop": "remove",
        "label": "Remove",
        "type": "VARIANT",
        "options": {
          "No": "false",
          "Yes": "true"
        }
      }
    ],
    "toggles": []
  },
  "Toggle": {
    "figma": "1526:5703",
    "own": [
      {
        "prop": "size",
        "label": "Size",
        "type": "VARIANT",
        "options": {
          "Small": "small",
          "Medium": "medium",
          "Large": "large"
        }
      },
      {
        "prop": "state",
        "label": "State",
        "type": "VARIANT",
        "options": {
          "Default": "default",
          "Disabled": "disabled"
        }
      },
      {
        "prop": "checked",
        "label": "Select",
        "type": "VARIANT",
        "options": {
          "No": "false",
          "Yes": "true"
        }
      },
      {
        "prop": "theme",
        "label": "Theme",
        "type": "VARIANT",
        "options": {
          "Text-First": "text-first",
          "Toggle-First": "toggle-first"
        }
      }
    ],
    "toggles": []
  },
  "ToggleButton": {
    "figma": "1523:104",
    "own": [
      {
        "prop": "size",
        "label": "Size",
        "type": "VARIANT",
        "options": {
          "Large": "large",
          "Medium": "medium",
          "Small": "small"
        }
      },
      {
        "prop": "state",
        "label": "State",
        "type": "VARIANT",
        "options": {
          "Default": "default",
          "Disabled": "disabled",
          "Default-Hover": "hover"
        }
      },
      {
        "prop": "checked",
        "label": "Select",
        "type": "VARIANT",
        "options": {
          "Yes": "true",
          "No": "false"
        }
      }
    ],
    "toggles": []
  },
  "Tooltip": {
    "figma": "1595:2220",
    "own": [
      {
        "prop": "color",
        "label": "Color",
        "type": "VARIANT",
        "options": {
          "Default": "default",
          "Accent": "accent",
          "White Overlay": "white-overlay",
          "Black-Overlay": "black-overlay"
        }
      },
      {
        "prop": "size",
        "label": "Size",
        "type": "VARIANT",
        "options": {
          "Medium": "medium",
          "Small": "small"
        }
      }
    ],
    "toggles": []
  },
  "Toast": {
    "figma": "1579:13276",
    "own": [
      {
        "prop": "title",
        "label": "Title-Text",
        "type": "TEXT"
      },
      {
        "prop": "type",
        "label": "Type",
        "type": "VARIANT",
        "options": {
          "Neutral": "neutral",
          "Subtle": "subtle",
          "Info": "info",
          "Positive": "positive",
          "Warning": "warning",
          "Negative": "negative"
        }
      }
    ],
    "toggles": []
  },
  "FileUpload": {
    "figma": "1581:22708",
    "own": [
      {
        "prop": "type",
        "label": "Type",
        "type": "VARIANT",
        "options": {
          "Drag & Drop": "dropzone",
          "Browse Button": "button"
        }
      }
    ],
    "toggles": [
      {
        "label": "hasLabel",
        "prop": "label",
        "on": "Attachments"
      },
      {
        "label": "hasHelperText",
        "prop": "helpText",
        "on": "Up to 5 files."
      }
    ]
  },
  "BottomNavigation": {
    "figma": "4060:26671",
    "own": [
      {
        "prop": "type",
        "type": "SET",
        "options": {
          "Bottom-Navigation/Mobile/Default": "default",
          "Bottom-Navigation/Mobile/Floating": "floating",
          "Bottom-Navigation/Mobile/Floating-Glass": "floating-glass"
        }
      }
    ],
    "toggles": []
  },
  "ChatComposer": {
    "figma": "6182:56819",
    "own": [
      {
        "prop": "device",
        "label": "Device",
        "type": "VARIANT",
        "options": {
          "Desktop": "desktop",
          "Mobile": "mobile"
        }
      }
    ],
    "toggles": []
  },
  "ChatAvatarGroup": {
    "figma": "6340:46191",
    "own": [
      {
        "prop": "size",
        "label": "Size",
        "type": "VARIANT",
        "options": {
          "Medium": "medium",
          "Small": "small"
        }
      }
    ],
    "toggles": []
  },
  "AiChatField": {
    "figma": "12074:16888",
    "own": [
      {
        "prop": "fieldStyle",
        "label": "Style",
        "type": "VARIANT",
        "options": {
          "Default": "default",
          "Surface": "surface",
          "Liquid Glass": "liquid-glass"
        }
      }
    ],
    "toggles": []
  },
  "NumberField": {
    "figma": "421:10057",
    "own": [
      {
        "prop": "align",
        "type": "SET",
        "options": {
          "Input/Number-Align-Left": "left",
          "Input/Number-Align-Center": "center"
        }
      },
      {
        "prop": "size",
        "label": "Size",
        "type": "VARIANT",
        "options": {
          "Small": "small",
          "Medium (Base)": "medium",
          "Large": "large",
          "XLarge": "xlarge"
        }
      },
      {
        "prop": "state",
        "label": "State",
        "type": "VARIANT",
        "options": {
          "Default": "default",
          "Hover": "hover",
          "Focused": "focused",
          "Typing": "typing",
          "Inputted": "inputted",
          "Read-Only": "read-only",
          "Disabled": "disabled",
          "Inputted-Error": "inputted-error",
          "Blank-Error": "blank-error"
        }
      }
    ],
    "toggles": [
      {
        "label": "Help-Text",
        "prop": "helpText",
        "on": "Help text"
      },
      {
        "label": "Label",
        "prop": "label",
        "on": "Label"
      }
    ],
    "nested": [
      {
        "name": "Label",
        "figma": "387:3651",
        "when": "label",
        "own": [
          {
            "prop": "labelOptional",
            "label": "Optional",
            "type": "BOOLEAN"
          },
          {
            "prop": "labelTooltip",
            "label": "Tooltip-Icon",
            "type": "BOOLEAN"
          },
          {
            "prop": "labelAction",
            "label": "Action",
            "type": "BOOLEAN"
          },
          {
            "prop": "label",
            "label": "Label",
            "type": "TEXT"
          }
        ]
      },
      {
        "name": "Help-Text",
        "when": "helpText",
        "own": [
          {
            "prop": "helpText",
            "label": "Text",
            "type": "CODE"
          },
          {
            "prop": "helpTheme",
            "label": "Theme",
            "type": "CODE"
          },
          {
            "prop": "helpIcon",
            "label": "Icon",
            "type": "CODE"
          },
          {
            "prop": "characterLimit",
            "label": "Character limit",
            "type": "CODE"
          }
        ]
      }
    ]
  },
  "TextAreaField": {
    "figma": "450:7027",
    "own": [
      {
        "prop": "size",
        "label": "Size",
        "type": "VARIANT",
        "options": {
          "Small": "small",
          "Medium (Base)": "medium",
          "Large": "large"
        }
      },
      {
        "prop": "state",
        "label": "State",
        "type": "VARIANT",
        "options": {
          "Default": "default",
          "Hover": "hover",
          "Focused": "focused",
          "Typing": "typing",
          "Inputted": "inputted",
          "Read-Only": "read-only",
          "Disabled": "disabled",
          "Inputted-Error": "inputted-error",
          "Blank-Error": "blank-error"
        }
      }
    ],
    "toggles": [
      {
        "label": "Help-Text",
        "prop": "helpText",
        "on": "Help text"
      },
      {
        "label": "Label",
        "prop": "label",
        "on": "Label"
      }
    ],
    "nested": [
      {
        "name": "Label",
        "figma": "387:3651",
        "when": "label",
        "own": [
          {
            "prop": "labelOptional",
            "label": "Optional",
            "type": "BOOLEAN"
          },
          {
            "prop": "labelTooltip",
            "label": "Tooltip-Icon",
            "type": "BOOLEAN"
          },
          {
            "prop": "labelAction",
            "label": "Action",
            "type": "BOOLEAN"
          },
          {
            "prop": "label",
            "label": "Label",
            "type": "TEXT"
          }
        ]
      },
      {
        "name": "Help-Text",
        "when": "helpText",
        "own": [
          {
            "prop": "helpText",
            "label": "Text",
            "type": "CODE"
          },
          {
            "prop": "helpTheme",
            "label": "Theme",
            "type": "CODE"
          },
          {
            "prop": "helpIcon",
            "label": "Icon",
            "type": "CODE"
          },
          {
            "prop": "characterLimit",
            "label": "Character limit",
            "type": "CODE"
          }
        ]
      }
    ]
  },
  "DatePicker": {
    "figma": "895:31954",
    "own": [
      {
        "prop": "calendar",
        "type": "SET",
        "options": {
          "Date-Picker/Single-Calendar": "single",
          "Date-Picker/Dual-Calendar": "dual"
        }
      },
      {
        "prop": "timePicker",
        "label": "Time-Picker",
        "type": "BOOLEAN"
      },
      {
        "prop": "showActions",
        "label": "Actions",
        "type": "BOOLEAN"
      }
    ],
    "toggles": []
  },
  "Stepper": {
    "figma": "1625:8328",
    "own": [
      {
        "prop": "orientation",
        "type": "SET",
        "options": {
          "Stepper-Bar/Horizontal": "horizontal",
          "Stepper-Bar/Vertical": "vertical"
        }
      }
    ],
    "toggles": []
  },
  "Metric": {
    "figma": "595:55188",
    "own": [
      {
        "prop": "variant",
        "type": "SET",
        "options": {
          "Primitives/Metric/Metric-Inline/Icon-Highlight": "icon-highlight",
          "Primitives/Metric/Metric-Inline/Title-Highlight": "title-highlight"
        }
      },
      {
        "prop": "size",
        "label": "Size",
        "type": "VARIANT",
        "options": {
          "XLarge": "xlarge",
          "Large": "large",
          "Medium": "medium",
          "Small": "small",
          "XSmall": "xsmall"
        }
      }
    ],
    "toggles": []
  },
  "MetricCard": {
    "figma": "595:55188",
    "own": [
      {
        "prop": "variant",
        "type": "SET",
        "options": {
          "Primitives/Metric/Metric-Inline/Icon-Highlight": "icon-highlight",
          "Primitives/Metric/Metric-Inline/Title-Highlight": "title-highlight"
        }
      },
      {
        "prop": "size",
        "label": "Size",
        "type": "VARIANT",
        "options": {
          "XLarge": "xlarge",
          "Large": "large",
          "Medium": "medium",
          "Small": "small",
          "XSmall": "xsmall"
        }
      }
    ],
    "toggles": []
  },
  "ChatMessage": {
    "figma": "6349:64085",
    "own": [
      {
        "prop": "showName",
        "label": "Name",
        "type": "BOOLEAN"
      },
      {
        "prop": "side",
        "label": "Side",
        "type": "VARIANT",
        "options": {
          "Others": "others",
          "You": "you"
        }
      }
    ],
    "toggles": []
  },
  "ChatBubble": {
    "figma": "6349:59476",
    "own": [
      {
        "prop": "side",
        "type": "SET",
        "options": {
          "Chat/Bubble/Text-You": "you",
          "Chat/Bubble/Text-Others": "others"
        }
      },
      {
        "prop": "domain",
        "label": "Domain",
        "type": "VARIANT",
        "options": {
          "Social": "social",
          "Business": "business"
        }
      }
    ],
    "toggles": []
  },
  "ChatCall": {
    "figma": "6349:59813",
    "own": [
      {
        "prop": "type",
        "label": "Type",
        "type": "VARIANT",
        "options": {
          "Audio": "audio",
          "Video": "video"
        }
      },
      {
        "prop": "state",
        "label": "State",
        "type": "VARIANT",
        "options": {
          "In-Call": "in-call",
          "In-Missed": "in-missed",
          "Out-Call": "out-call",
          "Out-Missed": "out-missed"
        }
      }
    ],
    "toggles": []
  },
  "ChatFile": {
    "figma": "6182:57708",
    "own": [
      {
        "prop": "kind",
        "label": "Type",
        "type": "VARIANT",
        "options": {
          "Doc": "doc",
          "PDF": "pdf",
          "Sheet": "sheet",
          "Others": "other"
        }
      }
    ],
    "toggles": []
  },
  "ChatPhotos": {
    "figma": "6349:62779",
    "own": [
      {
        "prop": "side",
        "type": "SET",
        "options": {
          "Chat/Bubble/Photo-You": "you",
          "Chat/Bubble/Photo-Others": "others"
        }
      }
    ],
    "toggles": []
  },
  "ChatConversationItem": {
    "figma": "6331:34480",
    "own": [
      {
        "prop": "unread",
        "label": "Unread",
        "type": "VARIANT",
        "options": {
          "No": "false",
          "Yes": "true"
        }
      }
    ],
    "toggles": []
  },
  "AiChatBubble": {
    "figma": "4218:1270",
    "own": [
      {
        "prop": "side",
        "label": "Side",
        "type": "VARIANT",
        "options": {
          "You": "you",
          "AI": "ai"
        }
      }
    ],
    "toggles": []
  },
  "EmptyState": {
    "figma": "6085:25796",
    "own": [],
    "toggles": [
      {
        "label": "CTA",
        "prop": "primaryAction",
        "on": {
          "code": "{ label: \"Action\" }"
        }
      }
    ]
  },
  "InputConditionItem": {
    "figma": "373:97437",
    "own": [
      {
        "prop": "state",
        "label": "State",
        "type": "VARIANT",
        "options": {
          "Default": "default",
          "Success": "success",
          "Wrong": "wrong"
        }
      }
    ],
    "toggles": []
  },
  "ControlBarSelectItem": {
    "figma": "9021:27379",
    "own": [
      {
        "prop": "icon",
        "label": "Icon-Src",
        "type": "INSTANCE_SWAP"
      },
      {
        "prop": "theme",
        "label": "Theme",
        "type": "VARIANT",
        "options": {
          "Subtle": "subtle",
          "Solid": "solid",
          "Inverse": "inverse"
        }
      },
      {
        "prop": "state",
        "label": "State",
        "type": "VARIANT",
        "options": {
          "Default": "default",
          "Hover": "hover",
          "Selected": "selected"
        }
      }
    ],
    "toggles": []
  }
};
