// Generated by tools/studio/part-props-build.mjs from src/components/**/*.tsx: do not edit by hand.
/** Owner component → the components its JSX renders → their props it passes on unchanged → the owner prop. */
export const PART_PROPS: Readonly<Record<string, Readonly<Record<string, Readonly<Record<string, string>>>>>> = {
  "AiChatField": {
    "IconButton": {
      "disabled": "disabled"
    }
  },
  "AppShellAccount": {
    "Avatar": {
      "src": "src"
    }
  },
  "AppShellAction": {
    "IconButton": {
      "icon": "icon",
      "tooltip": "tooltip"
    },
    "NotificationDot": {
      "tone": "tone"
    }
  },
  "AutocompleteField": {
    "Button": {
      "disabled": "disabled"
    },
    "InputHelpText": {
      "icon": "helpIcon"
    },
    "InputLabel": {
      "disabled": "disabled"
    },
    "PopoverManualAddNew": {
      "createLabel": "createLabel"
    },
    "Tag": {
      "disabled": "disabled"
    }
  },
  "Breadcrumbs": {
    "BreadcrumbItem": {
      "emphasis": "emphasis"
    }
  },
  "ChartCard": {
    "Card": {
      "surface": "surface",
      "theme": "theme"
    },
    "Segmented": {
      "fullWidth": "rangesFullWidth",
      "options": "ranges",
      "value": "range"
    }
  },
  "ChatCall": {
    "ChatCardFooter": {
      "detail": "detail"
    }
  },
  "ChatComposer": {
    "ChatComposerReply": {
      "target": "replyTo"
    },
    "IconButton": {
      "disabled": "disabled"
    }
  },
  "ChatComposerReply": {
    "ChatReplyBody": {
      "target": "target"
    }
  },
  "ChatConversationItem": {
    "Avatar": {
      "status": "online"
    },
    "ChatAvatarGroup": {
      "online": "online",
      "people": "group"
    },
    "ListItem": {
      "selected": "selected"
    }
  },
  "ChatFile": {
    "ChatCardFooter": {
      "detail": "size"
    }
  },
  "ChatHoldLayer": {
    "ChatReactionPicker": {
      "value": "reaction"
    }
  },
  "ChatHoverActions": {
    "ChatReactionPicker": {
      "value": "reaction"
    },
    "Popover": {
      "autoFocus": "fromBubble"
    }
  },
  "ChatMessage": {
    "ChatBubble": {
      "domain": "domain",
      "side": "side"
    },
    "ChatHoldLayer": {
      "reaction": "reaction",
      "side": "side"
    },
    "ChatHoverActions": {
      "reaction": "reaction",
      "side": "side"
    },
    "ChatReactions": {
      "mine": "reaction",
      "reactions": "reactions",
      "side": "side"
    },
    "ChatReadList": {
      "people": "seenBy"
    },
    "ChatReplyQuote": {
      "side": "side",
      "target": "replyTo"
    }
  },
  "ChatReactionPicker": {
    "ChatEmojiPicker": {
      "value": "value"
    }
  },
  "ChatReactions": {
    "ChatReactorsPanel": {
      "device": "device",
      "mine": "mine",
      "reactions": "reactions",
      "side": "side"
    }
  },
  "ChatReactorsPanel": {
    "ChatReactorsList": {
      "glyph": "glyph",
      "mine": "mine",
      "reactions": "reactions"
    },
    "ChatReactorsPopover": {
      "anchorRef": "anchorRef",
      "side": "side"
    }
  },
  "ChatReplyQuote": {
    "ChatReplyBody": {
      "target": "target"
    }
  },
  "Checkbox": {
    "CheckboxMark": {
      "indeterminate": "indeterminate"
    }
  },
  "Chip": {
    "Avatar": {
      "alt": "photoAlt",
      "src": "photoSrc"
    },
    "BadgeCounter": {
      "value": "counter"
    },
    "Popover": {
      "items": "popoverItems",
      "label": "popoverLabel",
      "multiple": "popoverMultiple",
      "scrollBar": "popoverScrollBar",
      "search": "popoverSearch",
      "searchPlaceholder": "popoverSearchPlaceholder",
      "searchValue": "popoverSearchValue"
    },
    "PopoverManualAddNew": {
      "createLabel": "popoverCreateLabel",
      "items": "popoverItems",
      "label": "popoverLabel",
      "multiple": "popoverMultiple",
      "scrollBar": "popoverScrollBar",
      "searchPlaceholder": "popoverSearchPlaceholder",
      "searchValue": "popoverSearchValue"
    }
  },
  "ChipGroup": {
    "Chip": {
      "disabled": "disabled",
      "level": "level",
      "size": "size"
    }
  },
  "DateField": {
    "DatePicker": {
      "maxDate": "maxDate",
      "minDate": "minDate",
      "showActions": "datePickerActions",
      "today": "today"
    },
    "DatePickerSheet": {
      "maxDate": "maxDate",
      "minDate": "minDate",
      "today": "today"
    },
    "InputField": {
      "trailing": "trailing"
    }
  },
  "DatePicker": {
    "DatePickerAction": {
      "action": "action"
    }
  },
  "DatePickerAction": {
    "Button": {
      "disabled": "cancelDisabled"
    }
  },
  "DatePickerSheet": {
    "BottomSheet": {
      "title": "title"
    },
    "DatePicker": {
      "maxDate": "maxDate",
      "minDate": "minDate",
      "monthCount": "monthCount",
      "selectionMode": "selectionMode",
      "today": "today"
    }
  },
  "DatePickerTimeField": {
    "InputField": {
      "label": "label"
    },
    "InputLeadingTrailing": {
      "popoverLabel": "label"
    }
  },
  "DatePickerTimePicker": {
    "DatePickerTimeField": {
      "device": "device"
    }
  },
  "DefaultSidebarBrand": {
    "SidebarCollapseButton": {
      "collapsed": "collapsed"
    }
  },
  "Dialog": {
    "ModalActions": {
      "direction": "actionsDirection",
      "primaryAction": "primaryAction",
      "secondaryAction": "secondaryAction",
      "tertiaryAction": "tertiaryAction"
    }
  },
  "DockIcon": {
    "Icon": {
      "name": "icon"
    }
  },
  "EmptyState": {
    "EmptyStateIllustration": {
      "icon": "icon"
    }
  },
  "FieldLabel": {
    "InputLabel": {
      "action": "action",
      "disabled": "disabled",
      "optional": "optional",
      "tooltip": "tooltip"
    }
  },
  "FieldShell": {
    "FieldLabel": {
      "action": "labelAction",
      "label": "label",
      "optional": "labelOptional",
      "required": "required",
      "tooltip": "labelTooltip"
    },
    "FieldMessage": {
      "characterLimit": "characterLimit",
      "error": "error",
      "helpIcon": "helpIcon",
      "helpText": "helpText",
      "helpTheme": "helpTheme"
    }
  },
  "FileUpload": {
    "UploaderFileItem": {
      "thumbnail": "thumbnail"
    }
  },
  "Form": {
    "Stack": {
      "gap": "gap"
    }
  },
  "FormField": {
    "InputLabel": {
      "action": "labelAction",
      "optional": "optional",
      "tooltip": "labelTooltip"
    }
  },
  "Image": {
    "ImageMedia": {
      "alt": "alt",
      "fit": "fit",
      "loading": "loading",
      "src": "src"
    }
  },
  "InputField": {
    "FieldShell": {
      "helpIcon": "helpIcon",
      "helpText": "helpText",
      "helpTheme": "helpTheme",
      "label": "label",
      "labelAction": "labelAction",
      "labelOptional": "labelOptional",
      "labelTooltip": "labelTooltip",
      "leading": "leading",
      "required": "required",
      "trailing": "trailing"
    }
  },
  "InputLeadingTrailing": {
    "Popover": {
      "label": "popoverLabel"
    }
  },
  "ItemList": {
    "SidebarItemView": {
      "collapsed": "collapsed",
      "openItems": "openItems",
      "setOpenItems": "setOpenItems"
    }
  },
  "LineChart": {
    "PlotFrame": {
      "ariaLabel": "aria-label",
      "format": "format",
      "height": "height"
    }
  },
  "MenuItem": {
    "Icon": {
      "name": "icon"
    },
    "PopoverItem": {
      "caption": "caption",
      "disabled": "disabled",
      "label": "label"
    }
  },
  "Metric": {
    "DockIcon": {
      "background": "iconBackground",
      "emoji": "iconEmoji",
      "icon": "icon",
      "theme": "iconTheme"
    },
    "MetricColorDot": {
      "color": "metricColor"
    },
    "Tooltip": {
      "content": "hint"
    }
  },
  "MetricCard": {
    "Card": {
      "subAction": "subAction",
      "theme": "theme"
    }
  },
  "ModalForm": {
    "ModalActions": {
      "direction": "actionsDirection",
      "primaryAction": "primaryAction",
      "secondaryAction": "secondaryAction",
      "tertiaryAction": "tertiaryAction"
    }
  },
  "PageHeader": {
    "Heading": {
      "level": "headingLevel"
    }
  },
  "Pagination": {
    "PageSizeChip": {
      "options": "pageSizeOptions",
      "pageSize": "pageSize"
    },
    "PageSizeInput": {
      "pageSize": "pageSize"
    }
  },
  "Popover": {
    "Search": {
      "clearable": "searchClearable"
    }
  },
  "RichTextEditorBar": {
    "ControlBarSelectItem": {
      "theme": "theme"
    },
    "SelectField": {
      "value": "blockType"
    }
  },
  "RichTextField": {
    "FieldLabel": {
      "action": "labelAction",
      "label": "label",
      "optional": "labelOptional",
      "required": "required",
      "tooltip": "labelTooltip"
    },
    "FieldShell": {
      "helpIcon": "helpIcon",
      "helpText": "helpText",
      "helpTheme": "helpTheme"
    },
    "RichTextEditorBar": {
      "theme": "editorBarTheme"
    }
  },
  "Search": {
    "InputField": {
      "disabled": "disabled",
      "label": "label"
    },
    "InputLeadingTrailing": {
      "interactive": "filterInteractive",
      "options": "filterOptions",
      "value": "filterValue"
    }
  },
  "Segmented": {
    "SegmentedItem": {
      "disabled": "disabled",
      "level": "level"
    }
  },
  "SegmentedItem": {
    "BadgeCounter": {
      "value": "badge"
    }
  },
  "SelectField": {
    "BottomSheet": {
      "title": "popoverLabel"
    },
    "FieldShell": {
      "helpIcon": "helpIcon",
      "helpText": "helpText",
      "helpTheme": "helpTheme",
      "label": "label",
      "labelAction": "labelAction",
      "labelOptional": "labelOptional",
      "labelTooltip": "labelTooltip",
      "leading": "leading",
      "required": "required",
      "trailing": "trailing"
    },
    "Popover": {
      "label": "popoverLabel",
      "search": "popoverSearch",
      "searchPlaceholder": "popoverSearchPlaceholder"
    },
    "Search": {
      "placeholder": "popoverSearchPlaceholder"
    }
  },
  "SidePanel": {
    "ModalActions": {
      "primaryAction": "primaryAction",
      "secondaryAction": "secondaryAction"
    }
  },
  "Sidebar": {
    "SidebarPanel": {
      "brand": "brand",
      "footer": "footer",
      "search": "search",
      "searchCollapsed": "searchCollapsed",
      "sections": "sections"
    },
    "WorkspaceHeader": {
      "action": "headerAction",
      "items": "workspaceItems"
    }
  },
  "SidebarItemView": {
    "SidebarItemView": {
      "collapsed": "collapsed",
      "openItems": "openItems",
      "setOpenItems": "setOpenItems"
    }
  },
  "SidebarMenuSection": {
    "SidebarSectionTitle": {
      "action": "action",
      "label": "label"
    }
  },
  "SidebarPanel": {
    "DefaultSidebarBrand": {
      "collapsed": "collapsed"
    },
    "ItemList": {
      "collapsed": "collapsed",
      "openItems": "openItems",
      "sections": "sections",
      "setOpenItems": "setOpenItems"
    },
    "SidebarCollapseButton": {
      "collapsed": "collapsed"
    }
  },
  "SidebarSubMenu": {
    "ItemList": {
      "sections": "sections"
    }
  },
  "StackBarChart": {
    "PlotFrame": {
      "ariaLabel": "aria-label",
      "format": "format",
      "height": "height"
    }
  },
  "TabItem": {
    "BadgeCounter": {
      "value": "badge"
    }
  },
  "TableMedia": {
    "TableText": {
      "bold": "bold",
      "caption": "caption"
    }
  },
  "Tabs": {
    "TabItem": {
      "variant": "variant"
    }
  },
  "Tag": {
    "Avatar": {
      "src": "photoSrc"
    }
  },
  "TextAreaField": {
    "FieldShell": {
      "helpIcon": "helpIcon",
      "helpText": "helpText",
      "helpTheme": "helpTheme",
      "label": "label",
      "labelAction": "labelAction",
      "labelOptional": "labelOptional",
      "labelTooltip": "labelTooltip",
      "leading": "leading",
      "required": "required",
      "trailing": "trailing"
    }
  },
  "Thumbnail": {
    "ImageMedia": {
      "alt": "alt",
      "fit": "fit",
      "loading": "loading",
      "src": "src"
    }
  },
  "ToastProvider": {
    "ToastStack": {
      "duration": "duration",
      "max": "max",
      "placement": "placement"
    }
  },
  "Toggle": {
    "ToggleButton": {
      "disabled": "disabled",
      "state": "state"
    }
  },
  "ToggleListItem": {
    "ToggleButton": {
      "checked": "checked",
      "defaultChecked": "defaultChecked",
      "disabled": "disabled",
      "name": "name",
      "size": "toggleSize"
    }
  },
  "Tooltip": {
    "TooltipSurface": {
      "color": "color"
    }
  },
  "TopNavigation": {
    "TopNavigationActionButton": {
      "action": "leading"
    }
  },
  "VoiceAction": {
    "IconButton": {
      "disabled": "disabled",
      "icon": "icon"
    }
  },
  "ZenProvider": {
    "Component": {
      "lang": "locale"
    },
    "ToastProvider": {
      "placement": "toastPlacement"
    }
  }
};
