import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const sourceDir = path.join(root, "icons/source");
const outputPath = path.join(root, "src/icons/generated/iconData.ts");
const manifestPath = path.join(root, "src/icons/generated/icon-manifest.json");

const toKebab = (value) =>
  value
    .replace(/([a-z0-9])([A-Z])/g, "$1-$2")
    .replace(/[^a-zA-Z0-9]+/g, "-")
    .replace(/^-|-$/g, "")
    .toLowerCase();

const listSvgFiles = (directory) => {
  if (!fs.existsSync(directory)) return [];
  return fs.readdirSync(directory, { withFileTypes: true }).flatMap((entry) => {
    const absolutePath = path.join(directory, entry.name);
    if (entry.isDirectory()) return listSvgFiles(absolutePath);
    return entry.isFile() && entry.name.toLowerCase().endsWith(".svg") ? [absolutePath] : [];
  });
};

const rejectUnsafeSvg = (svg, file) => {
  const unsafePatterns = [
    [/<script\b/i, "script element"],
    [/<foreignObject\b/i, "foreignObject element"],
    [/\son[a-z]+\s*=/i, "event handler"],
    [/javascript:/i, "javascript URL"],
    [/<iframe\b/i, "iframe element"],
  ];
  for (const [pattern, label] of unsafePatterns) {
    if (pattern.test(svg)) throw new Error(`${file}: unsafe ${label}`);
  }
};

const parseLength = (value) => {
  const match = String(value ?? "").match(/^([0-9.]+)/);
  return match ? Number(match[1]) : null;
};

const parseSvg = (file) => {
  let svg = fs.readFileSync(file, "utf8").trim();
  rejectUnsafeSvg(svg, file);
  svg = svg.replace(/<\?xml[\s\S]*?\?>/gi, "").replace(/<!doctype[\s\S]*?>/gi, "").trim();

  const match = svg.match(/^<svg\b([^>]*)>([\s\S]*)<\/svg>$/i);
  if (!match) throw new Error(`${file}: expected one root <svg> element`);

  const attributes = match[1];
  let content = match[2].trim();
  const viewBoxMatch = attributes.match(/\bviewBox=["']([^"']+)["']/i);
  const widthMatch = attributes.match(/\bwidth=["']([^"']+)["']/i);
  const heightMatch = attributes.match(/\bheight=["']([^"']+)["']/i);
  const width = parseLength(widthMatch?.[1]);
  const height = parseLength(heightMatch?.[1]);
  const viewBox = viewBoxMatch?.[1] ?? (width && height ? `0 0 ${width} ${height}` : null);
  if (!viewBox) throw new Error(`${file}: missing viewBox and numeric width/height fallback`);

  const presentationAttributeNames = [
    "fill",
    "stroke",
    "color",
    "opacity",
    "fill-opacity",
    "stroke-opacity",
    "stroke-width",
    "stroke-linecap",
    "stroke-linejoin",
    "stroke-miterlimit",
    "fill-rule",
    "clip-rule",
  ];
  let rootPresentation = presentationAttributeNames
    .map((name) => attributes.match(new RegExp(`\\b${name}=["'][^"']+["']`, "i"))?.[0])
    .filter(Boolean)
    .join(" ");

  const visibleContent = content.replace(/<defs\b[\s\S]*?<\/defs>/gi, "");
  const paints = [...`${rootPresentation} ${visibleContent}`.matchAll(/\b(?:fill|stroke)=["']([^"']+)["']/gi)]
    .map((result) => result[1].trim())
    .filter((value) => !/^(none|currentColor)$/i.test(value) && !/^url\(/i.test(value));
  const uniquePaints = [...new Set(paints.map((value) => value.toLowerCase()))];
  const colorMode = uniquePaints.length <= 1 ? "monochrome" : "multicolor";

  if (colorMode === "monochrome") {
    const replacePaints = (value) => value.replace(
      /\b(fill|stroke)=["'](?!none["']|currentColor["']|url\()[^"']+["']/gi,
      '$1="currentColor"',
    );
    rootPresentation = rootPresentation.replace(
      /\b(fill|stroke)=["'](?!none["']|currentColor["']|url\()[^"']+["']/gi,
      '$1="currentColor"',
    );
    content = content
      .split(/(<defs\b[\s\S]*?<\/defs>)/gi)
      .map((part) => (/^<defs\b/i.test(part) ? part : replacePaints(part)))
      .join("");
  }

  if (rootPresentation) content = `<g ${rootPresentation}>${content}</g>`;

  return { viewBox, content, colorMode };
};

const files = listSvgFiles(sourceDir).sort();
const icons = files.map((file) => {
  const relativePath = path.relative(sourceDir, file).replace(/\.svg$/i, "");
  const name = toKebab(relativePath.split(path.sep).join("/"));
  if (!name) throw new Error(`${file}: could not derive an icon name`);
  return { name, source: path.relative(root, file), ...parseSvg(file) };
});

const duplicateNames = icons
  .map((icon) => icon.name)
  .filter((name, index, names) => names.indexOf(name) !== index);
if (duplicateNames.length) {
  throw new Error(`Duplicate generated icon names: ${[...new Set(duplicateNames)].join(", ")}`);
}

const data = Object.fromEntries(
  icons.map(({ name, viewBox, content, colorMode }) => [name, { viewBox, content, colorMode }]),
);
const output = [
  "/* Generated by `npm run icons:build`. Do not edit directly. */",
  'export type IconColorMode = "monochrome" | "multicolor";',
  "export type IconDefinition = {",
  "  readonly viewBox: string;",
  "  readonly content: string;",
  "  readonly colorMode: IconColorMode;",
  "};",
  "",
  `export const iconData = ${JSON.stringify(data, null, 2)} as const;`,
  "",
  "export type IconName = (keyof typeof iconData) extends never",
  "  ? string",
  "  : keyof typeof iconData;",
  "export const iconNames = Object.keys(iconData) as IconName[];",
  "export const getIconData = (name: IconName): IconDefinition | undefined =>",
  "  (iconData as Record<string, IconDefinition>)[name];",
  "",
].join("\n");

fs.mkdirSync(path.dirname(outputPath), { recursive: true });
fs.writeFileSync(outputPath, output);
fs.writeFileSync(
  manifestPath,
  `${JSON.stringify(
    {
      count: icons.length,
      monochrome: icons.filter((icon) => icon.colorMode === "monochrome").length,
      multicolor: icons.filter((icon) => icon.colorMode === "multicolor").length,
      icons: icons.map(({ name, source, viewBox, colorMode }) => ({
        name,
        source,
        viewBox,
        colorMode,
      })),
    },
    null,
    2,
  )}\n`,
);

console.log(`Generated ${icons.length} icons from ${files.length} SVG files.`);
