/**
 * Builds the Flag data from icons/flags (one 24×24 SVG per variant of the Figma "Flag" set, 7063:63834 on
 * 🍑 Iconography). `icons/flags/_names.json` keeps the Figma variant names (the `Name` property) in Figma's order.
 *   node scripts/build-flags.mjs          write src/components/Flag/flagNames.ts + flagData.ts
 *   node scripts/build-flags.mjs --check  fail when the generated files are stale
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const sourceDir = path.join(root, "icons/flags");
const namesPath = path.join(sourceDir, "_names.json");
const outDir = path.join(root, "src/components/Flag");
const slug = (name) => name.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
const unsafe = [/<script\b/i, /<foreignObject\b/i, /\son[a-z]+\s*=/i, /javascript:/i, /<iframe\b/i];

const names = JSON.parse(fs.readFileSync(namesPath, "utf8"));
const data = {};
for (const name of names) {
  const file = path.join(sourceDir, `${slug(name)}.svg`);
  let svg = fs.readFileSync(file, "utf8");
  for (const pattern of unsafe) if (pattern.test(svg)) throw new Error(`${file}: unsafe content ${pattern}`);
  // Inner markup only; the 24×24 clip rect equals the viewBox, so the clip wrapper and its defs go.
  let inner = svg.replace(/^[\s\S]*?<svg[^>]*>/, "").replace(/<\/svg>\s*$/, "");
  inner = inner.replace(/<defs>[\s\S]*?<\/defs>/g, (defs) => (/<(linearGradient|radialGradient|mask|pattern|filter)\b/.test(defs) ? defs : ""));
  inner = inner.replace(/<g clip-path="url\(#[^)]+\)">([\s\S]*?)<\/g><\/g>$/, "$1</g>");
  inner = inner.replace(/\s*\n\s*/g, "").replace(/>\s+</g, "><").trim();
  data[name] = inner;
}
const banner = "/* Generated by scripts/build-flags.mjs from icons/flags (Figma Flag set 7063:63834). Do not edit. */\n";
const namesTs = `${banner}/** Every Figma Flag variant, by its \`Name\` (spelled as in Figma). */\nexport const flagNames = ${JSON.stringify(names, null, 0)} as const;\nexport type FlagName = (typeof flagNames)[number];\n`;
const dataTs = `${banner}/** 24×24 SVG markup per flag (loaded on demand by Flag). */\nconst flagData: Record<string, string> = ${JSON.stringify(data, null, 0)};\nexport default flagData;\n`;
const targets = [[path.join(outDir, "flagNames.ts"), namesTs], [path.join(outDir, "flagData.ts"), dataTs]];
if (process.argv.includes("--check")) {
  const stale = targets.filter(([file, text]) => !fs.existsSync(file) || fs.readFileSync(file, "utf8") !== text).map(([file]) => path.relative(root, file));
  if (stale.length) { console.error(`✗ Flag data is stale: ${stale.join(", ")} — run node scripts/build-flags.mjs`); process.exit(1); }
  console.log(`✓ Flag data up to date (${names.length} flags).`);
} else {
  fs.mkdirSync(outDir, { recursive: true });
  for (const [file, text] of targets) fs.writeFileSync(file, text);
  console.log(`✓ ${names.length} flags → src/components/Flag/flagNames.ts, flagData.ts (${Math.round(dataTs.length / 1024)} KB)`);
}
