/**
 * Assembles the public stylesheets of the library build (run after `vite build --config vite.lib.config.ts`).
 *
 *   dist/styles.css  Inter @font-face (url ./fonts/…) + tokens + text styles + effects + every component's CSS
 *   dist/reset.css   optional page reset (margins, box-sizing, Canvas background, Figma-matching text rendering)
 *   dist/fonts/      the Inter variable font files + licence
 *
 * Vite's lib mode inlines every asset as base64 (≈1.3 MB of font data inside the CSS), so the fonts are copied as
 * files instead. Platform-only styles (foundations.css, TASA Explorer, JetBrains Mono) never enter the package.
 *
 *   node scripts/build-lib-css.mjs [--out=dist]
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const outArg = process.argv.find((arg) => arg.startsWith("--out="));
const out = path.resolve(root, outArg ? outArg.slice(6) : process.env.ZEN_LIB_OUT ?? "dist");
const styles = path.join(root, "src/styles");
const read = (file) => fs.readFileSync(path.join(styles, file), "utf8").trim();

const componentsCss = path.join(out, "components.css");
if (!fs.existsSync(componentsCss)) {
  console.error(`✗ ${path.relative(root, componentsCss)} is missing — run the library build first (npm run build:lib).`);
  process.exit(1);
}

// Fonts: copy the files and point the @font-face urls at them.
const fontSource = path.join(root, "src/assets/fonts/Inter");
const fontOut = path.join(out, "fonts");
fs.mkdirSync(fontOut, { recursive: true });
for (const file of fs.readdirSync(fontSource)) fs.copyFileSync(path.join(fontSource, file), path.join(fontOut, file));
const fonts = read("fonts.css").replaceAll("../assets/fonts/Inter/", "./fonts/");

const banner = `/* @zen/design-system — generated by scripts/build-lib-css.mjs. Import once: import "@zen/design-system/styles.css"; */`;
const baseline = [
  "/* Zen components size with border-box even without reset.css. */",
  ':where([class*="zen-"]), :where([class*="zen-"])::before, :where([class*="zen-"])::after { box-sizing: border-box; }',
].join("\n");

const parts = [
  banner,
  fonts,
  "/* ── Tokens (Figma variables; modes via data-* attributes, see docs/getting-started.md) ── */",
  read("tokens.css"),
  "/* ── Text styles ── */",
  read("typography.css"),
  "/* ── Effect styles ── */",
  read("style-effects.css"),
  baseline,
  "/* ── Components ── */",
  fs.readFileSync(componentsCss, "utf8").trim(),
];
const css = `${parts.join("\n\n")}\n`;

const problems = [];
if (/data:font|data:application\/font|base64,d09G/i.test(css)) problems.push("inlined font data");
// The Dev font-family token may name JetBrains Mono (apps load it themselves); only the platform @font-face must stay out.
if (/@font-face\s*{[^}]*(TASA|JetBrains)/i.test(css)) problems.push("platform-only @font-face (TASA Explorer / JetBrains Mono)");
if (/\.foundation-|\.official-|\.pe-/.test(css)) problems.push("platform/docs class (.foundation-, .official-, .pe-)");
for (const match of css.matchAll(/url\(\s*["']?([^"')]+)["']?\s*\)/g)) {
  const target = match[1];
  if (target.startsWith("data:") || target.startsWith("#")) continue;
  if (!fs.existsSync(path.join(out, target))) problems.push(`broken url(${target})`);
}
if (problems.length) {
  console.error(`✗ styles.css: ${[...new Set(problems)].join("; ")}`);
  process.exit(1);
}

fs.writeFileSync(path.join(out, "styles.css"), css);
fs.writeFileSync(path.join(out, "reset.css"), `/* @zen/design-system — optional page reset. Import after styles.css. */\n${read("reset.css")}\n`);
fs.rmSync(componentsCss);

const kb = (bytes) => `${(bytes / 1024).toFixed(0)} KB`;
console.log(`✓ ${path.relative(root, path.join(out, "styles.css"))} ${kb(Buffer.byteLength(css))}, reset.css, fonts/ (${fs.readdirSync(fontOut).length} files)`);
