// Promote (Studio builder GĐ5 M5, spec docs/research/studio-builder-handoff-spec-2026-10-07.md §3e, the user's Q2): a
// builder page written into the repo as a template, `src/templates/studio/<Name>Template.tsx` (compile.mjs, the
// component named <Name>Template), its photos in `src/templates/studio/assets/` (a library photo copied from
// src/assets/media, an uploaded one from the browser), then TypeScript on the file. The dev server's POST /promote
// (vite-plugin-zen-studio.mjs) runs it for an admin, adds the harness, and never opens a pull request (`npm run ship`).
//
//   planPromotion(text, { file, uploads }) → { name, component, file, code, assets, missing } | { error }
//   writePromotion(root, plan, { overwrite }) → { written } | { conflict }
//   typecheck(root, files, { cacheDir }) → { ok, errors }
import { execFile } from "node:child_process";
import fs from "node:fs";
import fsp from "node:fs/promises";
import path from "node:path";
import { compileReact } from "./compile.mjs";

export const PROMOTE_DIR = "src/templates/studio";
/** Where the library's photos are (their `zen-media:` key is the file's name, builder/library/media.ts). */
const MEDIA_DIR = "src/assets/media";
/**
 * The repo file of a `zen-media:` key (builder/library/media.ts MEDIA_FILES): `tpl.<template>.<file>` a template's own
 * asset, a key with its extension that file in the media folder, else `<key>.webp` there.
 */
export function mediaSource(key) {
  const template = /^tpl\.([\w-]+)\.(.+)$/.exec(key);
  if (template) return `src/templates/${template[1]}/assets/${template[2]}`;
  return `${MEDIA_DIR}/${/\.[a-z0-9]+$/i.test(key) ? key : `${key}.webp`}`;
}

/** TypeScript on a promoted file must finish within this. */
const TSC_TIMEOUT = 120_000;

/**
 * What Promote writes for the page `text` into `dir`: the template's code and each photo it imports (`uploads`: the
 * uploaded photos' bytes by id, from the browser). `missing`: photos neither the repo nor the request holds.
 */
export function planPromotion(text, { file, uploads = {}, dir = PROMOTE_DIR } = {}) {
  const compiled = compileReact(text, { file, suffix: "Template" });
  if ("error" in compiled) return { error: compiled.error };
  const name = compiled.component;
  const assets = [];
  const missing = [];
  for (const media of compiled.media) {
    const target = `${dir}/assets/${media.file}`;
    if (media.kind === "media") assets.push({ path: target, source: mediaSource(media.key) });
    else if (uploads[media.key]) assets.push({ path: target, data: uploads[media.key] });
    else missing.push(media.key);
  }
  const code = compiled.code.replace(/^\/\/ Generated by Zen Studio from (.+)\. Edit the design, then export again\.$/m, (_line, source) => `// Promoted by Zen Studio from ${source}. Edit the design, then promote again (it replaces this file).`);
  return { name, component: name, file: `${dir}/${name}.tsx`, code, assets, missing, screens: compiled.screens.length };
}

/** Writes the plan under `root`; an existing template with other code is a conflict unless `overwrite`. */
export async function writePromotion(root, plan, { overwrite = false } = {}) {
  const target = path.join(root, plan.file);
  const current = fs.existsSync(target) ? await fsp.readFile(target, "utf8") : null;
  if (current !== null && current !== plan.code && !overwrite) return { conflict: plan.file };
  const written = [];
  const write = async (rel, data) => {
    const abs = path.join(root, rel);
    await fsp.mkdir(path.dirname(abs), { recursive: true });
    // Atomic: a temporary file next to it, then a rename.
    const temp = `${abs}.${process.pid}.tmp`;
    await fsp.writeFile(temp, data);
    await fsp.rename(temp, abs);
    written.push(rel);
  };
  for (const asset of plan.assets) {
    const data = asset.data ?? (await fsp.readFile(path.join(root, asset.source)));
    const abs = path.join(root, asset.path);
    if (fs.existsSync(abs) && Buffer.compare(await fsp.readFile(abs), Buffer.from(data)) === 0) continue;
    await write(asset.path, data);
  }
  if (current !== plan.code) await write(plan.file, plan.code);
  return { written };
}

/**
 * TypeScript on `files` (repo-relative) with the repo's settings and noUnusedLocals, as an app builds them: a tsconfig
 * in `cacheDir` that extends the repo's and includes only those files.
 */
export function typecheck(root, files, { cacheDir = "node_modules/.cache/zen-studio/promote-check" } = {}) {
  const dir = path.join(root, cacheDir);
  fs.mkdirSync(dir, { recursive: true });
  const config = path.join(dir, "tsconfig.json");
  fs.writeFileSync(config, JSON.stringify({
    extends: path.relative(dir, path.join(root, "tsconfig.json")),
    compilerOptions: { noUnusedLocals: true, noUnusedParameters: true, noEmit: true },
    include: [...files, "src/vite-env.d.ts"].map((file) => path.relative(dir, path.join(root, file))),
  }, null, 2));
  return new Promise((resolve) => {
    execFile(process.execPath, [path.join(root, "node_modules/typescript/bin/tsc"), "-p", config, "--pretty", "false"], { cwd: root, timeout: TSC_TIMEOUT, maxBuffer: 16 * 1024 * 1024, encoding: "utf8" }, (error, stdout, stderr) => {
      if (error && typeof error.code !== "number") { resolve({ ok: false, errors: [error.killed ? `TypeScript timed out after ${TSC_TIMEOUT / 1000} s` : String(error.message ?? error)] }); return; }
      // tsc names files relative to its working directory (the root); only the promoted files' errors count.
      const errors = `${stdout}\n${stderr}`.split(/\r?\n/).map((line) => line.trim()).filter((line) => / error TS\d+:/.test(line) && files.some((file) => line.startsWith(`${file}(`)));
      resolve({ ok: errors.length === 0, errors });
    });
  });
}
